import type {CSSProperties, ChangeEvent} from 'react';
import {Fragment, useEffect, useState} from 'react';
import type {DeckSlide} from './Deck.js';

const text = (value: unknown): string => typeof value === 'string' ? value : '';
const array = <T,>(value: unknown): ReadonlyArray<T> => Array.isArray(value) ? value as ReadonlyArray<T> : [];
type Card = {readonly title: string; readonly body: string};
type Item = {readonly label: string; readonly caption?: string; readonly detail?: string};
type Column = {readonly title: string; readonly items: ReadonlyArray<string>; readonly foot?: string};

const ICONS: Record<string, string> = { target: '<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="4"/><circle cx="12" cy="12" r="1"/>', shield: '<path d="M12 3l8 3v6c0 5-3.5 8-8 9-4.5-1-8-4-8-9V6z"/>', route: '<circle cx="6" cy="18" r="2"/><circle cx="18" cy="6" r="2"/><path d="M8 18h6a4 4 0 0 0 0-8H10a4 4 0 0 1 0-8h6"/>', inbox: '<path d="M3 13l2-8h14l2 8v6H3z"/><path d="M3 13h5l2 3h4l2-3h5"/>', check: '<circle cx="12" cy="12" r="9"/><path d="M8 12l3 3 5-6"/>', cross: '<circle cx="12" cy="12" r="9"/><path d="M9 9l6 6M15 9l-6 6"/>', gate: '<path d="M4 20V6l8-3 8 3v14"/><path d="M9 20v-7h6v7"/><path d="M4 12h16"/>', clock: '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>', users: '<circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2.5"/><path d="M3 19a6 6 0 0 1 12 0"/><path d="M15 19a4 4 0 0 1 6-3.5"/>', user: '<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>', file: '<path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4M9 12h6M9 16h6"/>', cpu: '<rect x="6" y="6" width="12" height="12" rx="2"/><rect x="10" y="10" width="4" height="4"/><path d="M9 2v4M15 2v4M9 18v4M15 18v4M2 9h4M2 15h4M18 9h4M18 15h4"/>', search: '<circle cx="11" cy="11" r="6"/><path d="M20 20l-4.5-4.5"/>', bulb: '<path d="M9 18h6M10 21h4"/><path d="M8 13a5 5 0 1 1 8 0c-1 1-1.5 2-1.5 3h-5c0-1-.5-2-1.5-3z"/>', flag: '<path d="M5 21V4"/><path d="M5 4h12l-2 4 2 4H5"/>', hand: '<path d="M8 12V6a1.5 1.5 0 0 1 3 0v5"/><path d="M11 11V4a1.5 1.5 0 0 1 3 0v7"/><path d="M14 11V6a1.5 1.5 0 0 1 3 0v8a6 6 0 0 1-12 0v-3a1.5 1.5 0 0 1 3 0v1"/>', play: '<path d="M7 5v14l11-7z"/>', repeat: '<path d="M4 12a8 8 0 0 1 14-5l2 2"/><path d="M20 4v5h-5"/><path d="M20 12a8 8 0 0 1-14 5l-2-2"/><path d="M4 20v-5h5"/>', stop: '<path d="M8 3h8l5 5v8l-5 5H8l-5-5V8z"/>', list: '<path d="M9 6h11M9 12h11M9 18h11"/><circle cx="4.5" cy="6" r="1.2"/><circle cx="4.5" cy="12" r="1.2"/><circle cx="4.5" cy="18" r="1.2"/>', dot: '<circle cx="12" cy="12" r="3"/>' };
const ICON_RULES: ReadonlyArray<readonly [RegExp, string]> = [[/goal|outcome|what$/, 'target'], [/boundar|guard|scope/, 'shield'], [/^stop/, 'stop'], [/^mode|route|during/, 'route'], [/input|source|read|deliver|include|contain/, 'inbox'], [/result|check|expected/, 'check'], [/must not|negative|problem|fail/, 'cross'], [/gate|decision/, 'gate'], [/open|time|when/, 'clock'], [/rotate|repeat|loop|again/, 'repeat'], [/group|mob|roles|team|squad|users|driver|navigator/, 'users'], [/individual|analyst|developer|tester|reviewer|observer|engineer|you/, 'user'], [/packet|claim|evidence|log|record|handoff|trace|contract|file|brief|plan|note|status/, 'file'], [/model|agent|adapter|tool|harness|hook|checker|cpu|subagent|session|repo|skill|mcp/, 'cpu'], [/review|search|inspect|compare/, 'search'], [/learned|why|idea|concept/, 'bulb'], [/can do|flag|deliver|ship|transfer|required output/, 'flag'], [/pick|choose|decide/, 'hand'], [/run|demo|execute|play|watch|ask/, 'play'], [/step|list|todo|checklist/, 'list']];
function iconKind(title: string): string { return ICON_RULES.find(([pattern]) => pattern.test(title.toLowerCase()))?.[1] ?? 'dot'; }
function CardIcon({title}: {readonly title: string}) { return <span className="card-icon"><svg viewBox="0 0 24 24" aria-hidden="true" dangerouslySetInnerHTML={{__html: ICONS[iconKind(title)] ?? ''}} /></span>; }
function CardBody({body}: {readonly body: string}) { const parts = body.split(/\s*(?:→|->)\s*/); return parts.length >= 3 && body.length < 200 ? <div className="chain">{parts.map((part, i) => <Fragment key={`${part}-${i}`}><span className={`chip${i === 0 ? ' first' : ''}`}>{part.trim()}</span>{i < parts.length - 1 && <span className="chain-arrow">→</span>}</Fragment>)}</div> : <p>{body}</p>; }
export function CardsRenderer({slide}: {readonly slide: DeckSlide}) { const cards = array<Card>(slide.cards); return <div className={`cards${cards.length === 3 ? ' three' : ''}`}>{cards.map((card, i) => <article className="card" style={{'--i': i} as CSSProperties} key={`${card.title}-${i}`}><div className="card-head"><CardIcon title={card.title}/><h2>{card.title}</h2></div><CardBody body={card.body}/></article>)}</div>; }
export function PillarsRenderer({slide}: {readonly slide: DeckSlide}) { return <div className="pillars">{array<Item>(slide.items).map((item, i) => <div className="pillar" style={{'--i': i} as CSSProperties} key={item.label}><span className="pillar-label">{item.label}</span>{item.caption && <span className="pillar-caption">{item.caption}</span>}</div>)}</div>; }
export function StepsRenderer({slide, revealStep, onRevealStepChange}: {readonly slide: DeckSlide; readonly revealStep: number; readonly onRevealStepChange?: (step: number) => void}) { const items = array<Item>(slide.items); const callout = slide.callout as {readonly at?: number; readonly text?: string} | undefined; const selected = Math.min(Math.max(revealStep, -1), items.length - 1); const revealNext = () => onRevealStepChange?.(Math.min(selected + 1, items.length - 1)); return <div className="steps-wrap"><ol className="steps-chain">{items.map((item, i) => <li className={`step-item${i === selected ? ' active' : ''}${callout?.at === i + 1 ? ' highlight' : ''}`} style={{'--i': i} as CSSProperties} key={item.label}>{callout?.at === i + 1 && <div className="step-callout"><span className="step-callout-text">{callout.text}</span><span className="step-callout-arrow">▼</span></div>}<button className="step-btn" type="button" aria-label={`Step ${i + 1}: ${item.label}`} aria-pressed={i === selected} onClick={() => onRevealStepChange?.(i)}><span className="step-circle">{i + 1}</span></button><span className="step-label">{item.label}</span>{item.caption && <span className="step-caption">{item.caption}</span>}</li>)}</ol><p className="steps-detail">{(selected >= 0 ? items[selected]?.detail || items[selected]?.caption || items[selected]?.label : text(slide.detail)) || ''}</p><div className="widget-controls"><button type="button" onClick={revealNext} disabled={selected >= items.length - 1}>Reveal next →</button><button type="button" className="secondary" onClick={() => onRevealStepChange?.(items.length - 1)}>Show all</button></div></div>; }
export function CompareRenderer({slide}: {readonly slide: DeckSlide}) { return <div className="compare">{array<Column>(slide.columns).map((column, i) => <section className="compare-col" style={{'--i': i} as CSSProperties} key={column.title}><h2>{column.title}</h2><ul>{column.items.map((item) => <li key={item}>{item}</li>)}</ul>{column.foot && <p className="compare-foot">{column.foot}</p>}</section>)}</div>; }
export function RecapRenderer({slide, revealStep, onRevealStepChange}: {readonly slide: DeckSlide; readonly revealStep: number; readonly onRevealStepChange?: (step: number) => void}) { const items = array<Item>(slide.items); const shown = Math.min(Math.max(revealStep + 1, 0), items.length); const reveal = () => onRevealStepChange?.(Math.min(shown, items.length - 1)); return <><ul className="recap-list">{items.map((item, i) => <li className={`recap-item ${i < shown ? '' : 'hidden-item'}`} aria-hidden={i >= shown} style={{'--i': i} as CSSProperties} key={item.label}><span className="recap-check">{i < shown ? '✓' : i + 1}</span><span className="recap-text">{item.label}{item.caption ? ` — ${item.caption}` : ''}</span></li>)}</ul><div className="widget-controls"><button type="button" onClick={reveal} disabled={shown >= items.length}>{shown >= items.length ? 'All shown' : shown === 0 ? `Reveal (${items.length})` : `Reveal (${items.length - shown} left)`}</button></div></>; }
function Timer() {
  const [minutes, setMinutes] = useState('');
  const [total, setTotal] = useState(0);
  const [left, setLeft] = useState(0);
  const [running, setRunning] = useState(false);
  const [finished, setFinished] = useState(false);
  const [paused, setPaused] = useState(false);
  useEffect(() => {
    if (!running) return;
    if (left <= 0) { setRunning(false); setFinished(true); return; }
    const id = window.setTimeout(() => setLeft((value) => value - 1), 1000);
    return () => window.clearTimeout(id);
  }, [running, left]);
  const applyMinutes = (value: string) => { const seconds = Math.max(0, Math.min(180, Math.floor(Number(value) || 0))) * 60; setTotal(seconds); setLeft(seconds); setFinished(false); setPaused(false); };
  const toggle = () => { if (running) { setRunning(false); setPaused(true); } else if (left > 0) { setRunning(true); setPaused(false); } };
  const face = finished ? 'TIME' : `${String(Math.floor(left / 60)).padStart(2, '0')}:${String(left % 60).padStart(2, '0')}`;
  return <div className={`timer${total > 0 && left <= 60 ? ' timer-late' : ''}`}><div className="timer-face">{face}</div><div className="timer-bar"><div className="timer-fill" style={total ? {width: `${100 * (1 - left / total)}%`} : undefined}/></div><div className="widget-controls"><label className="timer-field"><input type="number" min="0" max="180" step="1" placeholder="0" aria-label="Minutes for this assignment" value={minutes} disabled={running} onChange={(event) => { setMinutes(event.target.value); if (!running) applyMinutes(event.target.value); }} onKeyDown={(event) => { if (event.key === 'Enter') { event.preventDefault(); toggle(); } }}/><span>min</span></label><button type="button" onClick={toggle}>{running ? 'Pause' : paused ? 'Resume' : 'Start'}</button><button type="button" className="secondary" onClick={() => { setRunning(false); applyMinutes(minutes); }}>Reset</button></div></div>;
}
export function ImageRenderer({slide}: {readonly slide: DeckSlide}) { const src = text(slide.image); const caption = text(slide.imageCaption); return <>{src && <figure className="slide-figure"><img src={src} alt={text(slide.imageAlt) || slide.title} loading="lazy" decoding="async"/>{caption && <figcaption>{caption}</figcaption>}</figure>}{array<Card>(slide.cards).length > 0 && <CardsRenderer slide={slide}/>}</>; }
export function ExerciseRenderer({slide}: {readonly slide: DeckSlide}) { return <>{array<Card>(slide.cards).length > 0 && <CardsRenderer slide={slide}/>} <Timer/></>; }
export function LayoutRenderer({slide, revealStep, onRevealStepChange}: {readonly slide: DeckSlide; readonly revealStep: number; readonly onRevealStepChange?: (step: number) => void}) { switch (text(slide.layout)) { case 'pillars': return <PillarsRenderer slide={slide}/>; case 'steps': return <StepsRenderer slide={slide} revealStep={revealStep} {...(onRevealStepChange ? {onRevealStepChange} : {})}/>; case 'compare': return <CompareRenderer slide={slide}/>; case 'recap': return <RecapRenderer slide={slide} revealStep={revealStep} {...(onRevealStepChange ? {onRevealStepChange} : {})}/>; case 'exercise': return <ExerciseRenderer slide={slide}/>; case 'image': return <ImageRenderer slide={slide}/>; default: return <CardsRenderer slide={slide}/>; } }

export function Instructions({slide}: {readonly slide: DeckSlide}) { const steps = array<string>(slide.steps); const [done, setDone] = useState<ReadonlyArray<boolean>>(() => steps.map(() => false)); const [passed, setPassed] = useState(false); const onCheck = (event: ChangeEvent<HTMLInputElement>, index: number) => setDone((current) => current.map((value, i) => i === index ? event.target.checked : value)); if (steps.length === 0 && !slide.expected && !slide.check) return null; const count = done.filter(Boolean).length; const heading = text(slide.stepsHeading) || 'Your prompt must ask Claude Code to:'; return <section className={`exercise-instructions${count === steps.length && steps.length > 0 ? ' all-done' : ''}`}>{steps.length > 0 && <><div className="do-head"><h2>{heading}</h2><span className="do-count">{`${count} / ${steps.length}`}</span></div><ol className="do-list">{steps.map((step, i) => <li className={`do-item${done[i] ? ' done' : ''}`} key={step}><label><input type="checkbox" checked={done[i] ?? false} onChange={(event) => onCheck(event, i)}/><span className="do-text">{step}</span></label></li>)}</ol></>}{slide.expected && <p className="expected"><span className="field-label">Expected result</span><span>{slide.expected}</span></p>}{slide.check && <div className={`checkpoint${passed ? ' passed' : ''}`}><div className="checkpoint-top"><span className="field-label">Checkpoint</span><button type="button" className="checkpoint-toggle" aria-pressed={passed} onClick={() => setPassed((value) => !value)}>{passed ? 'Passed ✓' : 'Mark passed'}</button></div><p>{slide.check}</p></div>}</section>; }
