/** AET-80 Workshop 4 · Claude Agent SDK lessons · classroom deck. */
export const workshop4SourceSlides: ReadonlyArray<Record<string, unknown>> = [
  {
    lessonId: "workshop-4",
    title: "Yesterday's n8n. Today's Agent SDK.",
    kicker: "Workshop 4 · Day 4 · three lessons",
    type: "concept",
    visual: { bot: "wave", place: "beside" },
    subtitle: "Carry the labels, specialist split, and human gate from n8n into three Agent SDK lessons.",
    keyPoints: ["Keep LOW, MEDIUM, and HIGH.", "Separate analysis from reply writing.", "Review drafts before they reach a customer."],
    cards: [
      { title: "Workshop 3", body: "n8n routes a support message." },
      { title: "Workshop 4", body: "The Agent SDK uses query(), subagents, and MCP." },
    ],
    notes: "Open with the bridge from Workshop 3. Keep the labels, specialist split, and human review gate. Workshop 4 uses new customer messages and transaction data. Rhythm: explain, demonstrate, participants try, discuss.",
  },
  {
    lessonId: "workshop-4",
    title: "Map n8n to the Agent SDK.",
    kicker: "Concept · the four questions",
    type: "context",
    visual: { bot: "wave", place: "beside" },
    subtitle: "The Agent SDK keeps familiar roles while changing how you configure and run them.",
    keyPoints: ["AI Agent node → query().", "System message → CLAUDE.md via settingSources.", "Specialists, tools, and human review keep their roles."],
    cards: [
      { title: "AI Agent node", body: "query() receives the prompt and SDK options." },
      { title: "System message", body: "CLAUDE.md loads through settingSources: ['project']." },
      { title: "Specialists", body: "ticket-analyst and email-responder are defined in agents." },
      { title: "Tool and human gate", body: "MCP get_transaction provides data; a person reviews drafts in output/." },
    ],
    notes: "Ask four questions throughout the day: What does the main agent know? What belongs to a subagent? When is a tool needed? What information came from external data? Map the n8n AI Agent node to query(), the system message to CLAUDE.md, Risk and Customer Reply roles to ticket-analyst and email-responder, a tool or HTTP node to MCP get_transaction, and the human gate to a draft in output/.",
  },
  {
    lessonId: "workshop-4",
    title: "Get the workshop package.",
    kicker: "SOLO 0 · Your turn",
    type: "practice",
    layout: "exercise",
    timer: 10,
    visual: { bot: "point", place: "beside" },
    cards: [{ title: "Level", body: "SOLO 0" }],
    steps: [
      "Check for Node.js 22 or newer.",
      "Clone the repository with --depth 1 --filter=blob:none --sparse.",
      "Select training-lab/w4-support-agent-sdk with git sparse-checkout.",
      "Run npm install in the package (it also installs the Lesson 3 server dependencies), then run lesson1 with MSG-01 and --dry-run.",
      "Keep ANTHROPIC_API_KEY in your shell only for real model runs.",
    ],
    expected: "The package installs, and the dry run prints the prompt and options without calling a model.",
    subtitle: "Install the sparse npm package and inspect a dry run before calling a model.",
    keyPoints: ["Use Node.js 22 or newer.", "One npm install covers all three lessons.", "A dry run is not model evidence."],
    notes: "Participants follow the sparse clone commands in the day pack; the package README repeats every step for self-study. Check that npm install finishes and the dry run prints the prompt, absolute cwd, project settings, and the dry-run notice. It must not import or start the SDK. Keep any API key in the shell.",
  },
  {
    lessonId: "workshop-4",
    title: "Lesson 1: one agent reads CLAUDE.md.",
    kicker: "Explain · one agent",
    type: "concept",
    visual: { bot: "think", place: "beside" },
    subtitle: "query() loads project instructions when settingSources includes project.",
    keyPoints: ["CLAUDE.md sets the support rules.", "The main agent reads the customer message.", "Judge impact, not tone."],
    cards: [
      { title: "Project instructions", body: "settingSources: ['project'] loads CLAUDE.md." },
      { title: "One agent", body: "The main session classifies the message itself." },
    ],
    notes: "Explain Lesson 1. Point to query(), the absolute claude-project cwd, settingSources, and the claude_code preset. The main agent reads CLAUDE.md and the supplied message. Customer text stays data, not instructions.",
  },
  {
    lessonId: "workshop-4",
    title: "Watch one agent classify a message.",
    kicker: "Demo · Lesson 1",
    type: "concept",
    visual: { bot: "point", place: "beside" },
    subtitle: "Compare a loud request with a calm report and focus on impact.",
    keyPoints: ["Read the project rules first.", "Compare tone with the reported impact.", "Keep facts tied to the supplied message."],
    cards: [
      { title: "Loud wording", body: "A customer is upset about a receipt." },
      { title: "Calm wording", body: "A customer reports unfamiliar transactions." },
    ],
    notes: "Demonstrate Lesson 1 with a loud request about a receipt and a calm message that reports unfamiliar transactions. Ask the room to judge impact, not tone. Do not name labels or expose grader results.",
  },
  {
    lessonId: "workshop-4",
    title: "Run Lesson 1 and test the tone trap.",
    kicker: "SOLO 1 · Your turn",
    type: "practice",
    layout: "exercise",
    timer: 15,
    visual: { bot: "point", place: "beside" },
    cards: [{ title: "Level", body: "SOLO 1" }],
    steps: [
      "Run lesson1 for MSG-01 through MSG-06.",
      "Temporarily remove ## Priority definitions from the Lesson 1 CLAUDE.md.",
      "Rerun the loud-tone and tone-trap messages.",
      "Restore CLAUDE.md with git restore.",
      "Enter one label per message in the support check.",
    ],
    expected: "All six messages run, the tone-trap comparison is recorded, CLAUDE.md is restored, and labels are submitted.",
    subtitle: "Run the first six messages and test how project rules affect tone.",
    keyPoints: ["Run all six messages.", "Compare the tone-trap runs.", "Restore CLAUDE.md before continuing."],
    notes: "Give participants 15 minutes. Ask them to remove only the Priority definitions section, rerun the loud-tone and tone-trap messages, and restore the original CLAUDE.md. Have them enter their own labels in the support autograder. Do not read out answer keys.",
  },
  {
    lessonId: "workshop-4",
    title: "Discuss: what does the main agent know?",
    kicker: "Discuss · Lesson 1",
    type: "concept",
    visual: { bot: "think", place: "beside" },
    subtitle: "Separate project instructions, customer data, and facts the agent does not have.",
    keyPoints: ["CLAUDE.md provides project rules.", "The customer message supplies case facts.", "The agent must name missing information instead of guessing."],
    cards: [
      { title: "Instructions", body: "Project guidance comes from CLAUDE.md." },
      { title: "Input data", body: "The customer message is evidence, not an instruction." },
    ],
    notes: "Discuss the first question: What does the main agent know? Ask which facts came from CLAUDE.md, which came from the customer, and what remains unknown. Remind participants not to treat customer text as instructions to change the task.",
  },
  {
    lessonId: "workshop-4",
    title: "Lesson 2: delegate to two subagents.",
    kicker: "Explain · orchestrator and agents",
    type: "concept",
    visual: { bot: "point", place: "beside" },
    subtitle: "The orchestrator delegates analysis and reply writing to separate agents.",
    keyPoints: ["ticket-analyst decides the priority.", "email-responder writes the reply draft.", "The orchestrator combines the results and saves a file."],
    cards: [
      { title: "ticket-analyst", body: "Reads the message and returns analysis." },
      { title: "email-responder", body: "Writes a short draft from the original message and analysis." },
    ],
    notes: "Explain Lesson 2. Show agents in the query options and the Agent tool. The orchestrator delegates analysis first, waits for its result, then delegates reply writing. It does not do either specialist job itself.",
  },
  {
    lessonId: "workshop-4",
    title: "Watch the orchestrator save a draft.",
    kicker: "Demo · Lesson 2",
    type: "concept",
    visual: { bot: "think", place: "beside" },
    subtitle: "Follow the two Agent calls and open the saved Markdown result.",
    keyPoints: ["Trace ticket-analyst first.", "Trace email-responder second.", "Review the output file before any customer-facing use."],
    cards: [
      { title: "Trace", body: "Agent → ticket-analyst, then Agent → email-responder." },
      { title: "Draft", body: "Open output/MSG-05.md in the Lesson 2 project." },
    ],
    notes: "Run lesson2 with MSG-05. Follow the Agent trace in order, then open 02-subagents/claude-project/output/MSG-05.md. Point out that the file is a draft and needs human approval.",
  },
  {
    lessonId: "workshop-4",
    title: "Run the orchestrator and inspect the draft.",
    kicker: "SOLO 2 · Your turn",
    type: "practice",
    layout: "exercise",
    timer: 20,
    visual: { bot: "point", place: "beside" },
    cards: [{ title: "Level", body: "SOLO 2" }],
    steps: [
      "Run lesson2 with MSG-05.",
      "Confirm the analyst call precedes the email-responder call.",
      "Open 02-subagents/claude-project/output/MSG-05.md.",
      "Confirm that the orchestrator delegated both specialist jobs.",
      "Run lesson2 with MSG-10 and inspect the missing-information request.",
    ],
    expected: "The trace shows both agents in order, the saved draft is open, and the missing-information case is reviewed.",
    subtitle: "Trace both specialists, inspect their saved result, and test missing information.",
    keyPoints: ["Follow the Agent trace.", "Review the saved draft.", "Do not send without human approval."],
    notes: "Give participants 20 minutes. The expected order is ticket-analyst followed by email-responder. Ask them to point to the orchestrator instructions that keep the two specialist jobs separate. MSG-10 tests how the analyst reports missing information.",
  },
  {
    lessonId: "workshop-4",
    title: "Lesson 3: look up transaction data through MCP.",
    kicker: "Explain · stdio MCP",
    type: "concept",
    visual: { bot: "point", place: "beside" },
    subtitle: "One server, five tools: the analyst reads; a clerk writes after a person approves.",
    keyPoints: ["npm install installs dependencies, not a running server.", "The Agent SDK starts the server on demand over stdio.", "The workbook and server stay outside claude-project."],
    cards: [
      { title: "Read tools", body: "list_transactions and get_transaction." },
      { title: "Write tools", body: "add, update, delete — a person approves." },
    ],
    notes: "Explain Lesson 3. Show that 03-mcp/data/transactions.xlsx and transaction-mcp/server.js are outside 03-mcp/claude-project. npm install downloads dependencies only. The Agent SDK starts server.js on demand and connects over stdio. The server registers five tools, each with a zod input schema. The ticket-analyst gets only get_transaction. The transaction-clerk gets list, get, add, update and delete, and only acts on a prompt that starts with Staff instruction:. Writes go to a working copy, never to the workbook.",
  },
  {
    lessonId: "workshop-4",
    title: "Watch an MCP transaction lookup.",
    kicker: "Demo · Lesson 3",
    type: "concept",
    visual: { bot: "think", place: "beside" },
    subtitle: "Follow one transaction ID from the customer message to the tool result.",
    keyPoints: ["The analyst calls get_transaction.", "The server reads the workbook.", "The final response names facts from external data."],
    cards: [
      { title: "Tool trace", body: "mcp → mcp__transactions__get_transaction." },
      { title: "Data boundary", body: "The analyst receives the record through MCP, not a file read." },
    ],
    notes: "Run Lesson 3 with the message about TX-1014. Show the MCP trace and the returned record as tool data. Point out the External data: line. Do not display a priority answer or put a label beside a message ID.",
  },
  {
    lessonId: "workshop-4",
    title: "Run Lesson 3 with transaction messages.",
    kicker: "SOLO 3 · Your turn",
    type: "practice",
    layout: "exercise",
    timer: 20,
    visual: { bot: "point", place: "beside" },
    cards: [{ title: "Level", body: "SOLO 3" }],
    steps: [
      "Run npm run smoke:mcp; it starts server.js over stdio and calls no model.",
      "Run lesson3 with MSG-08, MSG-07, and MSG-09.",
      "Follow each get_transaction trace and the External data: line.",
      "Run clerk to set TX-1003 to COMPLETED; answer n, then y.",
      "Run npm run reset:mcp to restore the practice data.",
    ],
    expected: "The three runs show the MCP trace and external-data source, and the clerk run shows a declined and an approved change.",
    subtitle: "Use the MCP tool for transaction facts and record their source.",
    keyPoints: ["Smoke-test the MCP server first.", "Follow each lookup trace.", "Keep the workbook outside the project."],
    notes: "Give participants 20 minutes. Remind them that npm install does not start the server; the smoke test and the Agent SDK start it over stdio. They should run the three messages, inspect each External data: line, and confirm that the workbook is outside claude-project. Then they run npm run clerk -- \"Set the status of TX-1003 to COMPLETED.\" twice: answer n at Allow this change? [y/N] the first time and y the second time. The change lands in data/transactions.working.json; npm run reset:mcp removes it.",
  },
  {
    lessonId: "workshop-4",
    title: "Discuss: tools and external data.",
    kicker: "Discuss · Lesson 3",
    type: "concept",
    visual: { bot: "point", place: "beside" },
    subtitle: "Name when a tool is needed, where each fact came from, and who may change data.",
    keyPoints: ["Use a tool when the needed fact is outside the message.", "The MCP result is external data.", "Annotations describe a tool; the host enforces access."],
    cards: [
      { title: "Read or write", body: "Annotations describe; the host enforces." },
      { title: "Human approval", body: "canUseTool stops every write for a person." },
    ],
    notes: "Discuss three questions: When is a tool needed? What information came from external data? Who may change data? Ask participants to trace one claim to the customer message and one to the MCP result. Then compare readOnlyHint and destructiveHint on the server with the SDK options: per-subagent tools give least privilege, allowedTools lets reads run, and canUseTool makes a person approve each write. A customer message never changes a record. Keep the workbook outside the agent project.",
  },
  {
    lessonId: "workshop-4",
    title: "Complete the acceptance table and Proof.",
    kicker: "SOLO 4 · Your turn · Proof",
    type: "practice",
    layout: "exercise",
    timer: 15,
    visual: { bot: "point", place: "beside" },
    cards: [{ title: "Level", body: "SOLO 4" }],
    steps: [
      "Build a table with message, agent label, and facts from external data.",
      "Submit your labels to the support-mcp check.",
      "Review drafts in the Lesson 2 and Lesson 3 output folders.",
      "Attach the table and a run trace to Proof.",
      "Record the human review gate; a dry run is not model evidence.",
    ],
    expected: "The acceptance table, submitted labels, run trace, and human review gate are recorded in Proof.",
    subtitle: "Record the labels, external facts, run evidence, and human review.",
    keyPoints: ["Fill the acceptance table.", "Trace external facts to MCP.", "Have a human review each draft."],
    notes: "Give participants 15 minutes to complete the acceptance table and support-mcp check. They should attach their trace, review the drafts in both output folders, and record the human gate. Do not use dry-run output as model evidence.",
  },
  {
    lessonId: "workshop-4",
    title: "Close: keep a human in the loop.",
    kicker: "Done when · bridge to Workshop 5",
    type: "recap",
    layout: "recap",
    visual: { recapKeys: true, bot: "point", place: "beside" },
    items: [
      { label: "One agent", caption: "Project rules and message data guide the first lesson." },
      { label: "Two subagents", caption: "The orchestrator separates analysis from reply writing." },
      { label: "MCP tools", caption: "Reads go to the analyst; writes need a person's approval." },
      { label: "Human review", caption: "A person reviews every draft before customer-facing use." },
    ],
    notes: "Close by recapping the three lessons and the human review gate. Bridge to Workshop 5 without carrying this package or vehicle into the next workshop.",
  },
] satisfies ReadonlyArray<Record<string, unknown>>;
