import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash,createHmac,generateKeyPairSync,sign} from 'node:crypto';
import {mkdtempSync} from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createApp} from '../server/app.mjs';
import {readLoginState} from '../server/google-sso.mjs';

async function invoke(app,route,{body={},query={},cookies={}}={}){
 const layer=app.router.stack.find(candidate=>candidate.route?.path===route);assert.ok(layer,`Missing route ${route}`);const response={statusCode:200,headers:{},cookies:[],body:null};
 const req={body,query,headers:{cookie:Object.entries(cookies).map(([name,value])=>`${name}=${value}`).join('; ')}};
 const res={cookie(name,value,options={}){const attributes=[`${name}=${encodeURIComponent(value)}`,options.maxAge!==undefined&&`Max-Age=${Math.floor(options.maxAge/1000)}`,options.path&&`Path=${options.path}`,options.httpOnly&&'HttpOnly',options.secure&&'Secure',options.sameSite&&`SameSite=${options.sameSite[0].toUpperCase()+options.sameSite.slice(1)}`].filter(Boolean).join('; ');response.cookies.push(attributes);return this;},clearCookie(name,options={}){response.cookies.push(`${name}=; Path=${options.path||'/'}; Max-Age=0`);return this;},redirect(status,location){response.statusCode=status;response.headers.location=location;return this;},status(status){response.statusCode=status;return this;},json(value){response.body=value;return this;},end(){return this;}};
 await layer.route.stack[0].handle(req,res,error=>{response.statusCode=error.status||500;response.body={error:error.status?error.message:'Onverwachte serverfout. Probeer opnieuw; je invoer blijft staan.'};});return response;
}
const cookie=(response,name)=>response.cookies.map(value=>value.split(';')[0]).find(value=>value.startsWith(`${name}=`))?.slice(name.length+1);

test('Google login stays inert when its environment is absent',async()=>{const instance=createApp({dir:mkdtempSync(path.join(os.tmpdir(),'academy-sso-disabled-')),hostKey:'break-glass-key',publicBaseUrl:'http://127.0.0.1:4317',googleClientId:'',googleClientSecret:'',facilitatorDomains:''});assert.deepEqual((await invoke(instance.app,'/game/config')).body,{googleSso:false});});
test('Google login start is covered by the rate limiter',()=>{const instance=createApp({dir:mkdtempSync(path.join(os.tmpdir(),'academy-sso-rate-limit-')),hostKey:'break-glass-key',publicBaseUrl:'http://127.0.0.1:4317'});assert.ok(instance.app.router.stack.some(layer=>!layer.route&&layer.match?.('/auth/google/start')&&layer.handle.toString().includes('Te veel verzoeken. Wacht even.')));});
test('an empty host key makes createApp throw',()=>{assert.throws(()=>createApp({dir:mkdtempSync(path.join(os.tmpdir(),'academy-sso-empty-key-')),hostKey:'',publicBaseUrl:'http://127.0.0.1:4317'}),/ACADEMY_HOST_KEY of \.data\/host-key is leeg\./);});

test('Google facilitator login authorizes routes without weakening the host-key boundary',async()=>{
 const {publicKey,privateKey}=generateKeyPairSync('rsa',{modulusLength:2048}),jwk={...publicKey.export({format:'jwk'}),kid:'route-key',alg:'RS256',use:'sig'};let nonce;
 const encode=value=>Buffer.from(JSON.stringify(value)).toString('base64url'),issue=()=>{const header=encode({alg:'RS256',kid:jwk.kid}),now=Math.floor(Date.now()/1000),payload=encode({iss:'https://accounts.google.com',aud:'route-client',sub:'route-subject',email:'route@allowed.example',email_verified:true,name:'Route Facilitator',hd:'allowed.example',nonce,iat:now,exp:now+600}),signature=sign('RSA-SHA256',Buffer.from(`${header}.${payload}`),privateKey).toString('base64url');return `${header}.${payload}.${signature}`;};
 const fetchImpl=async url=>{if(url==='https://accounts.google.com/.well-known/openid-configuration')return Response.json({issuer:'https://accounts.google.com',authorization_endpoint:'https://accounts.google.com/o/oauth2/v2/auth',token_endpoint:'https://oauth2.googleapis.com/token',jwks_uri:'https://www.googleapis.com/oauth2/v3/certs'});if(url==='https://www.googleapis.com/oauth2/v3/certs')return Response.json({keys:[jwk]});if(url==='https://oauth2.googleapis.com/token')return Response.json({id_token:issue()});throw Error(`Unexpected URL ${url}`);};
 const signingSecret='route-signing-secret',loginSecret=createHmac('sha256',signingSecret).update('academy-login-state').digest(),instance=createApp({dir:mkdtempSync(path.join(os.tmpdir(),'academy-sso-routes-')),hostKey:'break-glass-key',signingSecret,publicBaseUrl:'https://academy.example.test',googleClientId:'route-client',googleClientSecret:'route-secret',facilitatorDomains:'allowed.example',fetchImpl});instance.proof.create=async()=>({slug:'route-proof',editor:'editor'});
 assert.deepEqual((await invoke(instance.app,'/game/config')).body,{googleSso:true});
 const start=await invoke(instance.app,'/auth/google/start');assert.equal(start.statusCode,302);const google=new URL(start.headers.location);assert.equal(google.origin,'https://accounts.google.com');for(const key of ['client_id','redirect_uri','state','nonce','code_challenge','code_challenge_method'])assert.ok(google.searchParams.get(key));assert.equal(google.searchParams.get('code_challenge_method'),'S256');assert.equal(google.searchParams.get('hd'),'allowed.example');assert.match(start.cookies.join('\n'),/HttpOnly/);assert.match(start.cookies.join('\n'),/SameSite=Lax/);assert.match(start.cookies.join('\n'),/Secure/);const loginCookie=cookie(start,'academy-login'),loginState=readLoginState(decodeURIComponent(loginCookie),loginSecret);nonce=loginState.nonce;assert.equal(loginState.state,google.searchParams.get('state'));
 const serverOnly=await invoke(instance.app,'/auth/google/callback',{query:{code:'authorization-code',state:loginState.state},cookies:{}});assert.equal(serverOnly.statusCode,302);assert.equal(serverOnly.headers.location,'/?facilitator=1');assert.ok(cookie(serverOnly,'academy-facilitator'));
 const serverReplay=await invoke(instance.app,'/auth/google/callback',{query:{code:'authorization-code',state:loginState.state},cookies:{}});assert.equal(serverReplay.statusCode,302);assert.equal(serverReplay.headers.location,'/?login_error=state');
 const expiredState='expired-server-state';await instance.store.loginStateSave({stateHash:createHash('sha256').update(expiredState).digest('hex'),nonce:'expired-nonce',codeVerifier:'expired-verifier',expiresAt:Date.now()-1});const expired=await invoke(instance.app,'/auth/google/callback',{query:{code:'authorization-code',state:expiredState},cookies:{}});assert.equal(expired.statusCode,302);assert.equal(expired.headers.location,'/?login_error=state');
 const cookieStart=await invoke(instance.app,'/auth/google/start');const cookieLogin=cookie(cookieStart,'academy-login'),cookieState=readLoginState(decodeURIComponent(cookieLogin),loginSecret);nonce=cookieState.nonce;const callback=await invoke(instance.app,'/auth/google/callback',{query:{code:'authorization-code',state:cookieState.state},cookies:{'academy-login':cookieLogin}});assert.equal(callback.statusCode,302);assert.equal(callback.headers.location,'/?facilitator=1');const facilitatorCookie=cookie(callback,'academy-facilitator');assert.ok(facilitatorCookie);
 const cookieReplay=await invoke(instance.app,'/auth/google/callback',{query:{code:'authorization-code',state:cookieState.state},cookies:{}});assert.equal(cookieReplay.statusCode,302);assert.equal(cookieReplay.headers.location,'/?login_error=state');
 const denied=await invoke(instance.app,'/game/create',{body:{name:'Denied squad'}});assert.equal(denied.statusCode,403);assert.deepEqual(denied.body,{error:'Ongeldige facilitator-startsleutel.'});
 const me=await invoke(instance.app,'/game/facilitator/me',{cookies:{'academy-facilitator':facilitatorCookie}});assert.equal(me.statusCode,200);assert.deepEqual(me.body,{email:'route@allowed.example',name:'Route Facilitator'});assert.equal((await invoke(instance.app,'/game/facilitator/me')).statusCode,401);
 const created=await invoke(instance.app,'/game/create',{body:{name:'SSO squad'},cookies:{'academy-facilitator':facilitatorCookie}});assert.equal(created.statusCode,200);assert.ok(created.body.token);const overview=await invoke(instance.app,'/game/facilitator/overview',{cookies:{'academy-facilitator':facilitatorCookie}});assert.equal(overview.statusCode,200);assert.deepEqual(overview.body[0].createdBy,{email:'route@allowed.example',name:'Route Facilitator'});const attached=await invoke(instance.app,'/game/facilitator/attach',{body:{roomId:created.body.roomId},cookies:{'academy-facilitator':facilitatorCookie}});assert.equal(instance.store.view(instance.store.auth(attached.body.token).r,instance.store.auth(attached.body.token).s).me.name,'Route Facilitator');
 const logout=await invoke(instance.app,'/auth/logout',{cookies:{'academy-facilitator':facilitatorCookie}});assert.equal(logout.statusCode,204);assert.match(logout.cookies.join('\n'),/academy-facilitator=;/);assert.equal((await invoke(instance.app,'/game/facilitator/me',{cookies:{'academy-facilitator':facilitatorCookie}})).statusCode,401);
});


test('facilitator session store failure redirects to login_error=session not verify',async()=>{
 const {publicKey,privateKey}=generateKeyPairSync('rsa',{modulusLength:2048}),jwk={...publicKey.export({format:'jwk'}),kid:'session-key',alg:'RS256',use:'sig'};let nonce;
 const encode=value=>Buffer.from(JSON.stringify(value)).toString('base64url'),issue=()=>{const header=encode({alg:'RS256',kid:jwk.kid}),now=Math.floor(Date.now()/1000),payload=encode({iss:'https://accounts.google.com',aud:'session-client',sub:'session-subject',email:'session@allowed.example',email_verified:true,name:'Session Facilitator',hd:'allowed.example',nonce,iat:now,exp:now+600}),signature=sign('RSA-SHA256',Buffer.from(`${header}.${payload}`),privateKey).toString('base64url');return `${header}.${payload}.${signature}`;};
 const fetchImpl=async url=>{if(url==='https://accounts.google.com/.well-known/openid-configuration')return Response.json({issuer:'https://accounts.google.com',authorization_endpoint:'https://accounts.google.com/o/oauth2/v2/auth',token_endpoint:'https://oauth2.googleapis.com/token',jwks_uri:'https://www.googleapis.com/oauth2/v3/certs'});if(url==='https://www.googleapis.com/oauth2/v3/certs')return Response.json({keys:[jwk]});if(url==='https://oauth2.googleapis.com/token')return Response.json({id_token:issue()});throw Error(`Unexpected URL ${url}`);};
 const signingSecret='session-signing-secret',loginSecret=createHmac('sha256',signingSecret).update('academy-login-state').digest(),instance=createApp({dir:mkdtempSync(path.join(os.tmpdir(),'academy-sso-session-')),hostKey:'break-glass-key',signingSecret,publicBaseUrl:'https://academy.example.test',googleClientId:'session-client',googleClientSecret:'session-secret',facilitatorDomains:'allowed.example',fetchImpl});
 const original=instance.store.facilitatorLogin.bind(instance.store);instance.store.facilitatorLogin=async()=>{throw Object.assign(new Error('insert into facilitator_sessions failed'),{code:undefined});};
 const start=await invoke(instance.app,'/auth/google/start');const loginCookie=cookie(start,'academy-login'),loginState=readLoginState(decodeURIComponent(loginCookie),loginSecret);nonce=loginState.nonce;
 const warnings=[];const warn=console.warn;console.warn=(...args)=>{warnings.push(args);};try{
  const failed=await invoke(instance.app,'/auth/google/callback',{query:{code:'authorization-code',state:loginState.state},cookies:{'academy-login':loginCookie}});
  assert.equal(failed.statusCode,302);assert.equal(failed.headers.location,'/?login_error=session');
  assert.ok(warnings.some(entry=>entry[0]==='[academy] Google-login mislukt'&&entry[1]?.code==='session'));
 }finally{console.warn=warn;instance.store.facilitatorLogin=original;}
});
