import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import os from 'node:os';import path from 'node:path';
import http from 'node:http';
import {Client,StreamableHTTPClientTransport} from '@modelcontextprotocol/client';import {createApp} from '../server/app.mjs';
test('Streamable HTTP scopes every call and rejects missing, invalid, browser and revoked tokens',async()=>{
 const reservation=http.createServer();await new Promise(r=>reservation.listen(0,'127.0.0.1',r));const port=reservation.address().port;await new Promise(r=>reservation.close(r));const publicBaseUrl=`https://127.0.0.1:${port}`;
 const dir=mkdtempSync(path.join(os.tmpdir(),'academy-remote-'));const instance=createApp({dir,hostKey:'test-host',publicBaseUrl});await new Promise(r=>instance.server.listen(port,'127.0.0.1',r));const base=`http://127.0.0.1:${instance.server.address().port}`;const clients=[];
 const headers=token=>({host:`127.0.0.1:${port}`,...(token?{authorization:'Bearer '+token}:{})});
 const request=async(route,token,body)=>fetch(base+route,{method:body?'POST':'GET',headers:{...headers(token),'content-type':'application/json'},body:body?JSON.stringify(body):undefined});
 try{
 const a=instance.store.create('A',{slug:'a'}),b=instance.store.create('B',{slug:'b'});const pa=instance.store.join(a.code,'A person'),pb=instance.store.join(b.code,'B person');const as=instance.store.auth(pa.token),bs=instance.store.auth(pb.token);const ta=instance.store.session(as.r.id,as.p.id,'mcp'),tb=instance.store.session(bs.r.id,bs.p.id,'mcp');instance.proof.state=async r=>({markdown:'Document '+r.proof.slug,marks:{}});
 for(const token of [undefined,'invalid',pa.token])assert.equal((await request('/mcp',token,{})).status,401);
 const connection=await (await request('/game/connection',pa.token)).json();assert.equal(connection.mcpUrl,publicBaseUrl+'/mcp');assert.equal(connection.remoteConfigured,true);
 async function connect(token,versionNegotiation){const c=new Client({name:'remote-test',version:'1'},versionNegotiation?{versionNegotiation}:undefined);await c.connect(new StreamableHTTPClientTransport(new URL(base+'/mcp'),{requestInit:{headers:headers(token)}}));clients.push(c);return c;}
 const ca=await connect(ta,{mode:{pin:'2026-07-28'}}),cb=await connect(tb);const tool=async(c,name,args={})=>JSON.parse((await c.callTool({name,arguments:args})).content[0].text);
 assert.equal(ca.getProtocolEra(),'modern');assert.equal(cb.getProtocolEra(),'legacy');const expectedTools=['get_mission','get_document','get_screen_state','search_knowledge','submit_evidence','suggest_document','list_decks','get_deck','create_deck','add_slide','update_slide','patch_deck','export_deck_html'];for(const c of [ca,cb])assert.deepEqual((await c.listTools()).tools.map(t=>t.name).sort(),[...expectedTools].sort());assert.equal((await tool(ca,'get_mission')).mission.id,'CLASSROOM-01');assert.equal((await tool(cb,'get_mission')).mission.id,'CLASSROOM-01');assert.equal((await tool(ca,'get_document',{roomId:bs.r.id,slug:'b'})).markdown,'Document a');assert.equal((await tool(cb,'get_document')).markdown,'Document b');
 assert.equal((await request('/game/control',ta,{action:'next'})).status,401);assert.equal((await request('/mcp',ta)).status,405);
 const badHost=await new Promise((resolve,reject)=>{const r=http.request(base+'/mcp',{method:'POST',headers:{...headers(ta),host:'attacker.test','content-type':'application/json',accept:'application/json, text/event-stream'}},res=>{res.resume();resolve(res.statusCode);});r.on('error',reject);r.end('{}');});assert.equal(badHost,403);
 const badOrigin=await fetch(base+'/mcp',{method:'POST',headers:{...headers(ta),origin:'https://attacker.test','content-type':'application/json'},body:'{}'});assert.equal(badOrigin.status,403);
 const replacement=await (await request('/game/mcp-token',pa.token,{})).json();assert(replacement.token);assert.equal((await request('/mcp',ta,{})).status,401);await assert.rejects(()=>ca.listTools());assert.equal((await cb.listTools()).tools.length,expectedTools.length);
 }finally{for(const c of clients)await c.close();await new Promise(r=>instance.server.close(r));rmSync(dir,{recursive:true,force:true});}
});
