import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync} from 'node:fs';import os from 'node:os';import path from 'node:path';import {Store} from '../server/store.mjs';
function fixture(count=5){const store=new Store(mkdtempSync(path.join(os.tmpdir(),'academy-test-')));const host=store.create('Test squad',{slug:'test'});const names=Array.from({length:count},(_,i)=>String.fromCharCode(65+i));const members=names.map(name=>store.join(host.code,name));return {store,host,members,r:store.auth(host.token).r};}
test('soft max 12, exactly one driver, rotation preserves document and SDLC',()=>{const {store,host,members,r}=fixture(5);assert.equal(r.members.length,5);for(const name of ['F','G','H','I','J','K','L'])store.join(host.code,name);assert.equal(r.members.length,12);assert.throws(()=>store.join(host.code,'M'),/vol/);const driven=new Set();store.control(r,'phase','Test');for(let i=0;i<5;i++){const view=store.view(r,store.auth(members[0].token).s);assert.equal(view.members.filter(m=>m.role==='Driver').length,1);driven.add(view.members.find(m=>m.role==='Driver').id);store.control(r,'next');}assert.equal(driven.size,5);assert.equal(r.phase,'Test');assert.equal(r.proof.slug,'test');});
test('soft rejoin restores seat and progress without a blank seat',()=>{const {store,host,r}=fixture(4);const first=store.auth(store.join(host.code,'Zoe').token);const person=r.members.find(m=>m.name==='Zoe');person.quiz={score:2,at:1,day:1};person.route='guided';person.progressByDay={'1':{quizScore:2}};store.save();const again=store.join(host.code,'zoe');assert.equal(again.rejoined,true);assert.equal(r.members.filter(m=>m.name.toLowerCase()==='zoe').length,1);const auth=store.auth(again.token);assert.equal(auth.p.id,person.id);assert.equal(auth.p.route,'guided');assert.equal(auth.p.quiz.score,2);});
test('shuffle randomizes driver among members',()=>{const {store,r}=fixture(4);const before=r.driver;const seen=new Set([before]);for(let i=0;i<40;i++){store.control(r,'shuffle');seen.add(r.driver);}assert.ok(seen.size>1);assert.equal(r.members.filter((_,i)=>i===r.driver).length,1);const view=store.view(r,{personId:'facilitator',displayName:'Facilitator'});assert.equal(view.members.filter(m=>m.role==='Driver').length,1);assert.ok(view.members.every(m=>m.role==='Driver'||m.role==='Navigator'));});
test('timer pause, resume, expiry never rotates',()=>{const {store,r}=fixture();store.control(r,'start',null,1000);assert.equal(store.remaining(r,11000),1490);store.control(r,'pause',null,11000);assert.equal(store.remaining(r,100000),1490);store.control(r,'start',null,100000);assert.equal(store.remaining(r,1600000),0);assert.equal(r.round,1);assert.equal(r.driver,0);});
test('private diagnostics and separate MCP credentials survive restart',()=>{const {store,members,r}=fixture();const a=store.auth(members[0].token);r.members[1].quiz={score:1};r.members[1].route='guided';const v=store.view(r,a.s);assert.equal(v.members[1].quiz,undefined);assert.equal(v.members[1].route,undefined);assert.throws(()=>store.auth(members[0].token,'mcp'),/toegang/);const token=store.session(r.id,a.p.id,'mcp');assert.throws(()=>store.auth(token,'browser'),/toegang/);assert.equal(new Store(store.dir).auth(token,'mcp').p.name,'A');});
test('cannot start practice before four members',()=>{const s=new Store(mkdtempSync(path.join(os.tmpdir(),'academy-small-')));const h=s.create('Small',{slug:'s'});s.join(h.code,'A');assert.throws(()=>s.control(s.auth(h.token).r,'start'),/minimaal 4/);});
test('facilitator can set remaining time and round duration',()=>{const {store,r}=fixture();store.control(r,'start',null,1000);store.control(r,'time',600,2000);assert.equal(r.remaining,600);assert.equal(r.deadline,602000);store.control(r,'duration',900);store.control(r,'next');assert.equal(r.remaining,900);});
test('invalid time and duration values fail with status 400',()=>{const {store,r}=fixture();for(const value of [-1,7201,1.5,'600'])assert.throws(()=>store.control(r,'time',value),error=>error.status===400);for(const value of [0,59,7201,1.5,'900'])assert.throws(()=>store.control(r,'duration',value),error=>error.status===400);});
test('facilitator can attach a second session to an existing room',()=>{const {store,host,r}=fixture();const attached=store.attachFacilitator(r.id);assert.notEqual(attached.token,host.token);assert.equal(attached.roomId,r.id);assert.equal(attached.code,host.code);const auth=store.auth(attached.token,'browser');assert.equal(auth.s.personId,'facilitator');assert.equal(store.view(r,auth.s).me.role,'Facilitator');assert.throws(()=>store.attachFacilitator('unknown-room'),error=>error.status===404);});
test('overview lists squads newest first with member roles and evidence counts',()=>{const store=new Store(mkdtempSync(path.join(os.tmpdir(),'academy-overview-')));const first=store.create('First squad',{slug:'first'});const second=store.create('Second squad',{slug:'second'});const firstRoom=store.auth(first.token).r;const secondRoom=store.auth(second.token).r;for(const name of ['A','B','C','D'])store.join(first.code,name);for(const name of ['E','F','G','H'])store.join(second.code,name);firstRoom.createdAt=1000;secondRoom.createdAt=2000;secondRoom.driver=1;firstRoom.evidence.push({id:'first-evidence'});secondRoom.evidence.push({id:'second-evidence-1'},{id:'second-evidence-2'});store.save();const rooms=store.overview();assert.deepEqual(rooms.map(room=>room.name),['Second squad','First squad']);assert.deepEqual(rooms[0].members.map(member=>member.role),['Navigator','Driver','Navigator','Navigator']);assert.equal(rooms[0].evidence,2);assert.equal(rooms[1].evidence,1);});
