CREATE TABLE "academy_curriculum"."glossary_terms" (
	"id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"course_id" uuid NOT NULL,
	"version" integer NOT NULL,
	"locale" text NOT NULL,
	"term" text NOT NULL,
	"definition" text NOT NULL,
	"search_en" "tsvector" GENERATED ALWAYS AS (setweight(to_tsvector('english'::regconfig, coalesce("term", '')), 'A') || setweight(to_tsvector('english'::regconfig, coalesce("definition", '')), 'B')) STORED NOT NULL,
	"search_nl" "tsvector" GENERATED ALWAYS AS (setweight(to_tsvector('dutch'::regconfig, coalesce("term", '')), 'A') || setweight(to_tsvector('dutch'::regconfig, coalesce("definition", '')), 'B')) STORED NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "glossary_terms_id_course_id_version_pk" PRIMARY KEY("id","course_id","version"),
	CONSTRAINT "glossary_terms_course_version_locale_term_key" UNIQUE("course_id","version","locale","term")
);
--> statement-breakpoint
ALTER TABLE "academy_curriculum"."assignments" ADD COLUMN "search_en" "tsvector" GENERATED ALWAYS AS (setweight(jsonb_to_tsvector('english'::regconfig, coalesce("title", '{}'::jsonb), '["string"]'::jsonb), 'A') || setweight(jsonb_to_tsvector('english'::regconfig, coalesce("goal", '{}'::jsonb), '["string"]'::jsonb), 'B') || setweight(jsonb_to_tsvector('english'::regconfig, coalesce("steps", '{}'::jsonb), '["string"]'::jsonb), 'C') || setweight(jsonb_to_tsvector('english'::regconfig, coalesce("checks", '{}'::jsonb), '["string"]'::jsonb), 'C') || setweight(jsonb_to_tsvector('english'::regconfig, coalesce("allowed", '{}'::jsonb), '["string"]'::jsonb), 'C') || setweight(to_tsvector('english'::regconfig, coalesce("expected", '')), 'B') || setweight(to_tsvector('english'::regconfig, coalesce("check", '')), 'B') || setweight(to_tsvector('english'::regconfig, coalesce("stop", '')), 'B') || setweight(to_tsvector('english'::regconfig, coalesce("stretch", '')), 'B')) STORED NOT NULL;--> statement-breakpoint
ALTER TABLE "academy_curriculum"."assignments" ADD COLUMN "search_nl" "tsvector" GENERATED ALWAYS AS (setweight(jsonb_to_tsvector('dutch'::regconfig, coalesce("title", '{}'::jsonb), '["string"]'::jsonb), 'A') || setweight(jsonb_to_tsvector('dutch'::regconfig, coalesce("goal", '{}'::jsonb), '["string"]'::jsonb), 'B') || setweight(jsonb_to_tsvector('dutch'::regconfig, coalesce("steps", '{}'::jsonb), '["string"]'::jsonb), 'C') || setweight(jsonb_to_tsvector('dutch'::regconfig, coalesce("checks", '{}'::jsonb), '["string"]'::jsonb), 'C') || setweight(jsonb_to_tsvector('dutch'::regconfig, coalesce("allowed", '{}'::jsonb), '["string"]'::jsonb), 'C') || setweight(to_tsvector('dutch'::regconfig, coalesce("expected", '')), 'B') || setweight(to_tsvector('dutch'::regconfig, coalesce("check", '')), 'B') || setweight(to_tsvector('dutch'::regconfig, coalesce("stop", '')), 'B') || setweight(to_tsvector('dutch'::regconfig, coalesce("stretch", '')), 'B')) STORED NOT NULL;--> statement-breakpoint
ALTER TABLE "academy_curriculum"."assignments" ADD COLUMN "private_search_en" "tsvector" GENERATED ALWAYS AS (setweight(jsonb_to_tsvector('english'::regconfig, coalesce("hints", '{}'::jsonb), '["string"]'::jsonb), 'C')) STORED NOT NULL;--> statement-breakpoint
ALTER TABLE "academy_curriculum"."assignments" ADD COLUMN "private_search_nl" "tsvector" GENERATED ALWAYS AS (setweight(jsonb_to_tsvector('dutch'::regconfig, coalesce("hints", '{}'::jsonb), '["string"]'::jsonb), 'C')) STORED NOT NULL;--> statement-breakpoint
ALTER TABLE "academy_curriculum"."slides" ADD COLUMN "search_en" "tsvector" GENERATED ALWAYS AS (setweight(to_tsvector('english'::regconfig, coalesce("title", '')), 'A') || setweight(to_tsvector('english'::regconfig, coalesce("kicker", '')), 'B') || setweight(to_tsvector('english'::regconfig, coalesce("subtitle", '')), 'B') || setweight(to_tsvector('english'::regconfig, coalesce("expected", '')), 'B') || setweight(to_tsvector('english'::regconfig, coalesce("check", '')), 'B') || setweight(to_tsvector('english'::regconfig, coalesce("prompt", '')), 'B') || setweight(to_tsvector('english'::regconfig, coalesce("tagline", '')), 'B') || setweight(to_tsvector('english'::regconfig, coalesce("plan_b", '')), 'B') || setweight(to_tsvector('english'::regconfig, coalesce("image_alt", '')), 'B') || setweight(to_tsvector('english'::regconfig, coalesce("image_caption", '')), 'B') || setweight(jsonb_to_tsvector('english'::regconfig, coalesce("cards", '{}'::jsonb), '["string"]'::jsonb), 'C') || setweight(jsonb_to_tsvector('english'::regconfig, coalesce("items", '{}'::jsonb), '["string"]'::jsonb), 'C') || setweight(jsonb_to_tsvector('english'::regconfig, coalesce("columns", '{}'::jsonb), '["string"]'::jsonb), 'C') || setweight(jsonb_to_tsvector('english'::regconfig, coalesce("steps", '{}'::jsonb), '["string"]'::jsonb), 'C') || setweight(jsonb_to_tsvector('english'::regconfig, coalesce("concepts", '{}'::jsonb), '["string"]'::jsonb), 'C') || setweight(jsonb_to_tsvector('english'::regconfig, coalesce("bars", '{}'::jsonb), '["string"]'::jsonb), 'C')) STORED NOT NULL;--> statement-breakpoint
ALTER TABLE "academy_curriculum"."slides" ADD COLUMN "search_nl" "tsvector" GENERATED ALWAYS AS (setweight(to_tsvector('dutch'::regconfig, coalesce("title", '')), 'A') || setweight(to_tsvector('dutch'::regconfig, coalesce("kicker", '')), 'B') || setweight(to_tsvector('dutch'::regconfig, coalesce("subtitle", '')), 'B') || setweight(to_tsvector('dutch'::regconfig, coalesce("expected", '')), 'B') || setweight(to_tsvector('dutch'::regconfig, coalesce("check", '')), 'B') || setweight(to_tsvector('dutch'::regconfig, coalesce("prompt", '')), 'B') || setweight(to_tsvector('dutch'::regconfig, coalesce("tagline", '')), 'B') || setweight(to_tsvector('dutch'::regconfig, coalesce("plan_b", '')), 'B') || setweight(to_tsvector('dutch'::regconfig, coalesce("image_alt", '')), 'B') || setweight(to_tsvector('dutch'::regconfig, coalesce("image_caption", '')), 'B') || setweight(jsonb_to_tsvector('dutch'::regconfig, coalesce("cards", '{}'::jsonb), '["string"]'::jsonb), 'C') || setweight(jsonb_to_tsvector('dutch'::regconfig, coalesce("items", '{}'::jsonb), '["string"]'::jsonb), 'C') || setweight(jsonb_to_tsvector('dutch'::regconfig, coalesce("columns", '{}'::jsonb), '["string"]'::jsonb), 'C') || setweight(jsonb_to_tsvector('dutch'::regconfig, coalesce("steps", '{}'::jsonb), '["string"]'::jsonb), 'C') || setweight(jsonb_to_tsvector('dutch'::regconfig, coalesce("concepts", '{}'::jsonb), '["string"]'::jsonb), 'C') || setweight(jsonb_to_tsvector('dutch'::regconfig, coalesce("bars", '{}'::jsonb), '["string"]'::jsonb), 'C')) STORED NOT NULL;--> statement-breakpoint
ALTER TABLE "academy_curriculum"."slides" ADD COLUMN "private_search_en" "tsvector" GENERATED ALWAYS AS (setweight(to_tsvector('english'::regconfig, coalesce("notes", '')), 'B')) STORED NOT NULL;--> statement-breakpoint
ALTER TABLE "academy_curriculum"."slides" ADD COLUMN "private_search_nl" "tsvector" GENERATED ALWAYS AS (setweight(to_tsvector('dutch'::regconfig, coalesce("notes", '')), 'B')) STORED NOT NULL;--> statement-breakpoint
ALTER TABLE "academy_curriculum"."glossary_terms" ADD CONSTRAINT "glossary_terms_course_id_version_course_versions_course_id_version_fk" FOREIGN KEY ("course_id","version") REFERENCES "academy_curriculum"."course_versions"("course_id","version") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "glossary_terms_search_en_idx" ON "academy_curriculum"."glossary_terms" USING gin ("search_en");--> statement-breakpoint
CREATE INDEX "glossary_terms_search_nl_idx" ON "academy_curriculum"."glossary_terms" USING gin ("search_nl");--> statement-breakpoint
CREATE INDEX "assignments_search_en_idx" ON "academy_curriculum"."assignments" USING gin ("search_en");--> statement-breakpoint
CREATE INDEX "assignments_search_nl_idx" ON "academy_curriculum"."assignments" USING gin ("search_nl");--> statement-breakpoint
CREATE INDEX "assignments_private_search_en_idx" ON "academy_curriculum"."assignments" USING gin ("private_search_en");--> statement-breakpoint
CREATE INDEX "assignments_private_search_nl_idx" ON "academy_curriculum"."assignments" USING gin ("private_search_nl");--> statement-breakpoint
CREATE INDEX "slides_search_en_idx" ON "academy_curriculum"."slides" USING gin ("search_en");--> statement-breakpoint
CREATE INDEX "slides_search_nl_idx" ON "academy_curriculum"."slides" USING gin ("search_nl");--> statement-breakpoint
CREATE INDEX "slides_private_search_en_idx" ON "academy_curriculum"."slides" USING gin ("private_search_en");--> statement-breakpoint
CREATE INDEX "slides_private_search_nl_idx" ON "academy_curriculum"."slides" USING gin ("private_search_nl");--> statement-breakpoint
-- Hand-appended (drizzle-kit cannot emit triggers): glossary rows follow the
-- same publish-immutability rule as every other content table (see 0001).
CREATE TRIGGER "glossary_terms_content_immutable"
  BEFORE INSERT OR UPDATE OR DELETE ON "academy_curriculum"."glossary_terms"
  FOR EACH ROW EXECUTE FUNCTION "academy_curriculum"."forbid_mutate_published_content"();
