import {fileURLToPath} from 'node:url';
import {DAY_PACKS} from '../content/days/index.mjs';
import {normalizeContentLocale,projectPackLocale} from '../content/days/locale.mjs';
import {assertValidDayPacks} from './day-pack-lint.mjs';
import {courseOrder} from '../content/days/course.mjs';
const LESSON_COPY = [
 ['L1-INTENT',{en:['A shared north star','Describe the problem before the solution. Write down who is affected, what has to improve and which observable evidence counts. People decide the goal and the acceptance.','Make an opportunity/responsibility map: current task, desired task, and one decision AI does not take on its own.'],nl:['Een gedeelde north star','Beschrijf het probleem vóór de oplossing. Noteer wie er last van heeft, wat beter moet en welk observeerbaar bewijs telt. De mens bepaalt het doel en de acceptatie.','Maak een opportunity/responsibility-map: huidige taak, gewenste taak, en één beslissing die AI niet zelfstandig neemt.']}],
 ['L1-SCOUT',{en:['Read first, then act','Have Claude Code first explore the working folder, files, goal and missing information. A README is a claim; check it against the files and runnable checks. Ask for paths and concrete observations.','Ask for a read-only repository scan with three paths, one uncertainty and a stop rule.'],nl:['Eerst lezen, dan handelen','Laat Claude Code eerst werkmap, bestanden, doel en ontbrekende informatie onderzoeken. Een README is een claim; controleer die tegen de bestanden en uitvoerbare checks. Vraag om paden en concrete observaties.','Vraag om een read-only repository-verkenning met drie paden, één onzekerheid en een stopregel.']}],
 ['L1-PLAN',{en:['The smallest useful step','Split the task into explore, plan, small change, verify and hand off. Give every step a result and a check. Choose one useful workflow; bigger is not proof of better.','Write a plan for one README fix. What is explicitly out of scope?'],nl:['De kleinste nuttige stap','Splits de taak in onderzoeken, plannen, kleine wijziging, verifiëren en overdragen. Geef iedere stap een resultaat en controle. Kies één nuttige workflow; groter is geen bewijs van beter.','Schrijf een plan voor één README-correctie. Wat valt expliciet buiten scope?']}],
 ['L2-CONTEXT',{en:['Context and recovery','Context is information for the current task. Keep lasting project agreements in CLAUDE.md, longer explanations in findable references and progress in a handoff. Secrets do not belong in shared context.','Restart with a fresh context: can someone else find the goal, decision, evidence and next step?'],nl:['Context en herstel','Context is informatie voor de huidige taak. Bewaar duurzame projectafspraken in CLAUDE.md, uitgebreide uitleg in vindbare referenties en voortgang in een overdracht. Geheimen horen niet in gedeelde context.','Herstart met een verse context: kan een ander doel, besluit, bewijs en volgende stap terugvinden?']}],
 ['L2-SKILLS',{en:['Instructions and skills','Project instructions describe fixed agreements; a skill describes a repeatable way of working. A skill on its own grants no access to a system. Use plain code or a template where that is enough.','Make a capability map: context, instruction, tool, skill and human judgement for this review.'],nl:['Instructies en skills','Projectinstructies beschrijven vaste afspraken; een skill beschrijft een herhaalbare werkwijze. Een skill geeft op zichzelf geen toegang tot een systeem. Gebruik gewone code of een sjabloon waar dat voldoende is.','Maak een capability-map: context, instructie, tool, skill en menselijk oordeel voor deze review.']}],
 ['L2-MCP',{en:['MCP and information boundaries','MCP exposes tools and information to an agent. The allowed tools and the room token limit access. The game cannot start your Claude Code remotely. A room token is not an Anthropic API key.','Read the mission and document through MCP. Ask for a suggestion; do not allow silent acceptance.'],nl:['MCP en informatiegrenzen','MCP ontsluit tools en informatie aan een agent. De toegestane tools en kamertoken begrenzen toegang. De game kan je Claude Code niet op afstand starten. Een kamertoken is geen Anthropic API-key.','Lees missie en document via MCP. Vraag om een suggestie; geef geen toestemming voor stilzwijgend accepteren.']}],
 ['L2-PERMISSIONS',{en:['Human decision points','Agree what the agent may read, propose and run. Stop on missing access, sensitive information or out-of-scope work. In this mission: read local fictional files and run checks; no client systems, push or deployment.','A tool wants access to Jira. Is that access needed for this local task? Explain your stop decision.'],nl:['Menselijke beslispunten','Spreek af wat de agent mag lezen, voorstellen en uitvoeren. Stop bij ontbrekende toegang, gevoelige informatie of werk buiten scope. In deze missie: lokale fictieve bestanden lezen en checks uitvoeren; geen client-systemen, push of deployment.','Een tool wil toegang tot Jira. Is die toegang nodig voor deze lokale taak? Licht je stopbesluit toe.']}],
 ['L2-EVIDENCE',{en:['Review, test and evidence','Tell a claim apart from a check that was run. Record the command, observed result, file reference and limitation. A green check only proves what that check measures. A person judges the conclusion.','Compare README and package.json. Deliver one reproducible finding, with the output quoted as observed.'],nl:['Review, test en bewijs','Onderscheid een claim van een uitgevoerde controle. Noteer commando, waargenomen resultaat, bestandsverwijzing en beperking. Een groene check bewijst alleen wat die check meet. Een mens beoordeelt de conclusie.','Vergelijk README en package.json. Lever één reproduceerbare bevinding, met letterlijk waargenomen uitvoer.']}],
 ['L2-HANDOFF',{en:['Handing off to a fresh reader','Record the goal, decisions, changed files, checks run, open risk and next owner. Have another participant run the check again. Agents agreeing is not an independent test.','Ask another participant to reproduce your finding and record the result before acceptance.'],nl:['Overdragen aan een verse lezer','Leg doel, besluiten, gewijzigde bestanden, uitgevoerde checks, open risico en volgende eigenaar vast. Laat een andere deelnemer de controle opnieuw uitvoeren. Agentovereenstemming is geen onafhankelijke test.','Vraag een andere deelnemer je bevinding te reproduceren en noteer het resultaat vóór acceptatie.']}],
 ['L2-WORKFLOW',{en:['Choose a fitting tool','Use a prompt for one-off thinking, a template or skill for repeatable instructions and deterministic automation for fixed rules. An agent fits when the work needs context-dependent steps and can be bounded in a testable way.','Design the smallest useful workflow: input, AI task, tools, human gate, verification and value.'],nl:['Kies een passend hulpmiddel','Gebruik een prompt voor incidenteel denkwerk, een sjabloon of skill voor herhaalbare instructies en deterministische automatisering voor vaste regels. Een agent is passend als het werk contextafhankelijke stappen vraagt en toetsbaar begrensd kan worden.','Ontwerp de kleinste nuttige workflow: input, AI-taak, tools, menselijke gate, verificatie en waarde.']}]
];
const LESSON_SOURCE={en:'MVP lesson derived from the approved intent document; not a verbatim copy of the class document.',nl:'MVP-les, afgeleid van het goedgekeurde intent-document; geen letterlijke weergave van het klasdocument.'};
const lessonsFor=locale=>LESSON_COPY.map(([id,copy])=>{const [title,body,exercise]=copy[locale];return {id,title,body,exercise,source:LESSON_SOURCE[locale]};});
const LESSONS={en:lessonsFor('en'),nl:lessonsFor('nl')};
export const lessons=LESSONS.en;
export const localizedLessons=locale=>LESSONS[normalizeContentLocale(locale)];
export const phases=['Plan','Design','Build','Test','Deploy','Maintain'];
export const mission={id:'ATLAS-REVIEW-01',title:'Make the repository understandable',minutes:25,goal:'Explore the fictional Atlas repository. Deliver one reproducible mismatch between the onboarding instructions and the project, plus a bounded improvement proposal.',allowed:['Read only the bundled starter files.','Run node --test in your own copy.','Submit evidence and a suggestion; a person decides on acceptance.'],stop:'Stop on missing files, secrets or access needed beyond the starter. Report what is missing; do not make up output.',checks:['Point to a concrete file and passage.','State the command you actually ran and its output.','Describe why this matters for the goal and what is not proven yet.'],lessonIds:['L1-SCOUT','L2-CONTEXT','L2-MCP','L2-EVIDENCE','L2-HANDOFF']};
export const initialDocument=`# Our intent\n\n## Problem\nNew team members cannot reliably start the fictional Atlas repository with the README alone.\n\n## Desired outcome\nA fresh reader can run the right check and explain the result.\n\n## Success criteria\nThe instructions match the available scripts. A second participant reproduces the check. Uncertainties stay visible.\n\n## Boundaries and ownership\nOnly the bundled starter. No client data, external systems, push or deployment. The squad records team decisions; participants explore and give feedback.\n\n## Plan and human decision point\nRead first, then back up one mismatch. The squad reviews evidence before a proposal is accepted.\n\n## Evidence and handoff\nRecord accepted findings, the check, limitations and the next owner here.\n`;
export function searchKnowledge(query='',locale='en'){const words=query.toLowerCase().trim().split(/\s+/).filter(Boolean);return localizedLessons(locale).filter(l=>!words.length||words.some(w=>`${l.id} ${l.title} ${l.body} ${l.exercise}`.toLowerCase().includes(w)));}

const dayPacks=Object.fromEntries(DAY_PACKS.map(pack=>[pack.day,pack]));
export function getDayPack(day){return dayPacks[day]??null;}
export function listDaySummaries(){return DAY_PACKS.map(pack=>{const projected=projectPackLocale(pack,'en');return {day:pack.day,title:projected.title,tag:projected.tag,blurb:projected.blurb};});}
export function listRouteDays(course=null){const summaries=Object.fromEntries(listDaySummaries().map(summary=>[summary.day,summary]));return courseOrder(course).map(({position,day,title,date})=>({...summaries[day],title:title??summaries[day].title,position,date,hasLesson:true}));}
export function courseEntry(course,day){return course?courseOrder(course).find(entry=>entry.day===day)??null:null;}
export const starterFileNames=['README.md','CLAUDE.md','package.json','status.mjs','status.test.mjs','n8n-repository-review.json','n8n-review-README.md','claude-code-review-README.md','day5-fictional-issue.md','n8n-triage-l1-switch.json','n8n-triage-l2-agent-memory.json','n8n-triage-l3-multi-agent.json','triage-fixtures.json','customer-messages.md'];
assertValidDayPacks(DAY_PACKS,{starterDir:fileURLToPath(new URL('../starter/',import.meta.url)),starterFileNames});
