import {fileURLToPath} from 'node:url';
import {DAY_PACKS} from '../content/days/index.mjs';
import {assertValidDayPacks} from './day-pack-lint.mjs';
import {courseOrder} from '../content/days/course.mjs';
export const lessons = [
 ['L1-INTENT','Een gedeelde north star','Beschrijf het probleem vóór de oplossing. Noteer wie er last van heeft, wat beter moet en welk observeerbaar bewijs telt. De mens bepaalt het doel en de acceptatie.','Maak een opportunity/responsibility-map: huidige taak, gewenste taak, en één beslissing die AI niet zelfstandig neemt.'],
 ['L1-SCOUT','Eerst lezen, dan handelen','Laat Claude Code eerst werkmap, bestanden, doel en ontbrekende informatie onderzoeken. Een README is een claim; controleer die tegen de bestanden en uitvoerbare checks. Vraag om paden en concrete observaties.','Vraag om een read-only repository-verkenning met drie paden, één onzekerheid en een stopregel.'],
 ['L1-PLAN','De kleinste nuttige stap','Splits de taak in onderzoeken, plannen, kleine wijziging, verifiëren en overdragen. Geef iedere stap een resultaat en controle. Kies één nuttige workflow; groter is geen bewijs van beter.','Schrijf een plan voor één README-correctie. Wat valt expliciet buiten scope?'],
 ['L2-CONTEXT','Context en herstel','Context is informatie voor de huidige taak. Bewaar duurzame projectafspraken in CLAUDE.md, uitgebreide uitleg in vindbare referenties en voortgang in een overdracht. Geheimen horen niet in gedeelde context.','Herstart met een verse context: kan een ander doel, besluit, bewijs en volgende stap terugvinden?'],
 ['L2-SKILLS','Instructies en skills','Projectinstructies beschrijven vaste afspraken; een skill beschrijft een herhaalbare werkwijze. Een skill geeft op zichzelf geen toegang tot een systeem. Gebruik gewone code of een sjabloon waar dat voldoende is.','Maak een capability-map: context, instructie, tool, skill en menselijk oordeel voor deze review.'],
 ['L2-MCP','MCP en informatiegrenzen','MCP ontsluit tools en informatie aan een agent. De toegestane tools en kamertoken begrenzen toegang. De game kan je Claude Code niet op afstand starten. Een kamertoken is geen Anthropic API-key.','Lees missie en document via MCP. Vraag om een suggestie; geef geen toestemming voor stilzwijgend accepteren.'],
 ['L2-PERMISSIONS','Menselijke beslispunten','Spreek af wat de agent mag lezen, voorstellen en uitvoeren. Stop bij ontbrekende toegang, gevoelige informatie of werk buiten scope. In deze missie: lokale fictieve bestanden lezen en checks uitvoeren; geen client-systemen, push of deployment.','Een tool wil toegang tot Jira. Is die toegang nodig voor deze lokale taak? Licht je stopbesluit toe.'],
 ['L2-EVIDENCE','Review, test en bewijs','Onderscheid een claim van een uitgevoerde controle. Noteer commando, waargenomen resultaat, bestandsverwijzing en beperking. Een groene check bewijst alleen wat die check meet. Een mens beoordeelt de conclusie.','Vergelijk README en package.json. Lever één reproduceerbare bevinding, met letterlijk waargenomen uitvoer.'],
 ['L2-HANDOFF','Overdragen aan een verse lezer','Leg doel, besluiten, gewijzigde bestanden, uitgevoerde checks, open risico en volgende eigenaar vast. Laat een andere deelnemer de controle opnieuw uitvoeren. Agentovereenstemming is geen onafhankelijke test.','Vraag een navigator je bevinding te reproduceren en noteer het resultaat vóór acceptatie.'],
 ['L2-WORKFLOW','Kies een passend hulpmiddel','Gebruik een prompt voor incidenteel denkwerk, een sjabloon of skill voor herhaalbare instructies en deterministische automatisering voor vaste regels. Een agent is passend als het werk contextafhankelijke stappen vraagt en toetsbaar begrensd kan worden.','Ontwerp de kleinste nuttige workflow: input, AI-taak, tools, menselijke gate, verificatie en waarde.']
].map(([id,title,body,exercise])=>({id,title,body,exercise,source:'MVP-les, afgeleid van het goedgekeurde intent-document; geen letterlijke weergave van het klasdocument.'}));
export const phases=['Plan','Design','Build','Test','Deploy','Maintain'];
export const mission={id:'ATLAS-REVIEW-01',title:'Maak de repository begrijpelijk',minutes:25,goal:'Onderzoek de fictieve Atlas-repository. Lever één reproduceerbare afwijking tussen de onboarding-instructies en het project, plus een begrensd verbetervoorstel.',allowed:['Lees alleen de meegeleverde starterbestanden.','Voer node --test uit in je eigen kopie.','Dien bewijs en een suggestie in; een mens beslist over acceptatie.'],stop:'Stop bij ontbrekende bestanden, geheimen of benodigde toegang buiten de starter. Meld wat ontbreekt; verzin geen uitvoer.',checks:['Verwijs naar een concreet bestand en passage.','Vermeld het werkelijk uitgevoerde commando en de uitvoer.','Beschrijf waarom dit het doel raakt en wat nog niet is bewezen.'],lessonIds:['L1-SCOUT','L2-CONTEXT','L2-MCP','L2-EVIDENCE','L2-HANDOFF']};
export const initialDocument=`# Onze intent\n\n## Probleem\nNieuwe teamleden kunnen de fictieve Atlas-repository niet betrouwbaar opstarten met alleen de README.\n\n## Gewenst resultaat\nEen verse lezer kan de juiste controle uitvoeren en de uitkomst uitleggen.\n\n## Succescriteria\nDe instructie komt overeen met de beschikbare scripts. Een tweede deelnemer reproduceert de controle. Onzekerheden blijven zichtbaar.\n\n## Grenzen en eigenaarschap\nAlleen de meegeleverde starter. Geen klantdata, externe systemen, push of deployment. De driver verwerkt teambesluiten; navigators onderzoeken en geven feedback.\n\n## Plan en menselijk beslispunt\nEerst lezen, dan één afwijking onderbouwen. De squad beoordeelt bewijs voordat een voorstel wordt geaccepteerd.\n\n## Bewijs en overdracht\nLeg hier geaccepteerde bevindingen, de controle, beperkingen en de volgende eigenaar vast.\n`;
export function searchKnowledge(query=''){const words=query.toLowerCase().trim().split(/\s+/).filter(Boolean);return lessons.filter(l=>!words.length||words.some(w=>`${l.id} ${l.title} ${l.body} ${l.exercise}`.toLowerCase().includes(w)));}

const dayPacks=Object.fromEntries(DAY_PACKS.map(pack=>[pack.day,pack]));
export function getDayPack(day){return dayPacks[day]??null;}
export function listDaySummaries(){return DAY_PACKS.map(({day,title,tag,blurb})=>({day,title,tag,blurb}));}
export function listRouteDays(course=null){const summaries=Object.fromEntries(listDaySummaries().map(summary=>[summary.day,summary]));return courseOrder(course).map(({position,day,title,date})=>({...summaries[day],title:title??summaries[day].title,position,date,hasLesson:true}));}
export function courseEntry(course,day){return course?courseOrder(course).find(entry=>entry.day===day)??null:null;}
export const starterFileNames=['README.md','CLAUDE.md','package.json','status.mjs','status.test.mjs','n8n-repository-review.json','n8n-review-README.md','claude-code-review-README.md','day5-fictional-issue.md','n8n-triage-l1-switch.json','n8n-triage-l2-agent-memory.json','n8n-triage-l3-multi-agent.json','triage-fixtures.json'];
assertValidDayPacks(DAY_PACKS,{starterDir:fileURLToPath(new URL('../starter/',import.meta.url)),starterFileNames});
