import {McpServer} from '@modelcontextprotocol/server';
import {z} from 'zod';
export function createAcademyMcpServer(call){
const server=new McpServer({name:'aetherlink-academy',version:'0.2.0'});
const invoke=(name,args,ctx)=>call(name,args,ctx).then(data=>({content:[{type:'text',text:JSON.stringify(data,null,2)}]})).catch(e=>({content:[{type:'text',text:e.message}],isError:true}));
server.registerTool('get_mission',{description:'Read the current mission, boundaries and help choice.'},async ctx=>invoke('get_mission',{},ctx));
server.registerTool('get_screen_state',{description:'Read what your own browser shows right now: view, deck slide, quiz and room. Released lessons only; no answers, notes or anyone else’s screen.'},async ctx=>invoke('get_screen_state',{},ctx));
server.registerTool('search_knowledge',{description:'Search all bundled curriculum lessons; cite the lesson ids. An empty query returns every lesson.',inputSchema:z.object({query:z.string().max(200).default('')})},async(args,ctx)=>invoke('search_knowledge',args,ctx));
server.registerTool('submit_evidence',{description:'Submit actually observed evidence as an attributed squad contribution. This does not accept it; keep the requestId when retrying.',inputSchema:z.object({requestId:z.string().min(1).max(100),finding:z.string().min(1).max(4000),command:z.string().min(1).max(1000),observed:z.string().min(1).max(4000),limitation:z.string().min(1).max(4000),taskId:z.string().min(1).max(100).optional().describe('Assignment id from get_mission.tasks; links this evidence to that assignment so the facilitator reviews it.')})},async(args,ctx)=>invoke('submit_evidence',args,ctx));
const text=max=>z.string().max(max);
const classroom=z.object({title:text(300).min(1),kicker:text(120).optional(),subtitle:text(600).optional(),type:z.enum(['context','concept','practice','review','quiz','recap','pause']).optional(),layout:z.enum(['cards','pillars','steps','compare','exercise','recap']).optional().describe('exercise = assignment with steps, timer and expected outcome.'),dark:z.boolean().optional(),hidden:z.boolean().optional(),cards:z.array(z.object({title:text(200),body:text(1500)})).max(12).optional(),items:z.array(z.object({label:text(200),caption:text(400).optional(),detail:text(1500).optional()})).max(12).optional().describe('For pillars/steps/recap.'),columns:z.array(z.object({title:text(200),items:z.array(text(500)).max(12),foot:text(400).optional()})).max(4).optional().describe('For compare.'),steps:z.array(text(500)).max(12).optional(),stepsHeading:text(200).optional(),expected:text(600).optional(),timer:z.number().int().min(1).max(120).optional().describe('Preset minutes for an exercise slide timer.'),check:text(600).optional(),prompt:text(4000).optional(),tagline:text(300).optional(),keyPoints:z.array(text(200)).max(8).optional().describe('Presenter view only.'),visual:z.record(z.string(),z.unknown()).optional().describe('Safe subset: bot, place, quiz{answer}, reveal:"click", stepThrough:true, stagger:"pop", spotlight, hero, checklist, countdown, quietTimer, stepKeys, recapKeys, levelUp, pairs, oneCol, phrase, highlight.')}).describe('Structured classroom slide (same fields as aetherlink-classroom-slides). Present with presenter view, reveals, quiz and timers at /decks/{deckId}.');
const slideInput={classroom:classroom.optional(),id:z.string().max(64).optional().describe('Stable slide id; omit it to have one generated.'),content:z.string().max(200000).optional().describe('Full slide HTML with the .fmd-slide wrapper. Omit it to have heading/body laid out.'),heading:z.string().max(300).optional(),body:z.array(z.string().max(1000)).max(12).optional().describe('Short bullets (at most 3 per slide for readability).'),label:z.string().max(120).optional().describe('Small section label above the title.'),layout:z.enum(['title','content','two-column','image','blank']).optional(),notes:z.string().max(20000).optional().describe('Speaker notes, not visible on the slide.'),background:z.string().max(200).optional(),transition:z.enum(['instant','none','fade','slide','zoom']).optional()};
const edit=z.union([
 z.object({op:z.literal('replace').optional(),find:z.string().min(1),replace:z.string(),occurrence:z.number().int().min(1).optional(),all:z.boolean().optional(),expectedMatches:z.number().int().min(0).optional(),required:z.boolean().optional()}),
 z.object({op:z.enum(['insert-before','insert-after']),find:z.string().min(1),content:z.string(),expectedMatches:z.number().int().min(0).optional(),required:z.boolean().optional()}),
 z.object({op:z.literal('replace-between'),start:z.string().min(1),end:z.string().min(1),replace:z.string(),expectedMatches:z.number().int().min(0).optional(),required:z.boolean().optional()}),
 z.object({op:z.literal('regex-replace'),pattern:z.string().min(1),flags:z.string().regex(/^[gimsuy]*$/).optional(),replace:z.string(),all:z.boolean().optional(),expectedMatches:z.number().int().min(0).optional(),required:z.boolean().optional()}),
]);
const operation=z.union([
 z.object({op:z.literal('patch-slide'),slideId:z.string(),fields:z.object({content:z.string().optional(),classroom:classroom.optional(),notes:z.string().optional(),layout:z.enum(['title','content','two-column','image','blank']).optional(),background:z.string().optional(),transition:z.enum(['instant','none','fade','slide','zoom']).optional()})}),
 z.object({op:z.literal('delete-slide'),slideId:z.string()}),
 z.object({op:z.literal('reorder-slides'),slideIds:z.array(z.string()).min(1)}),
 z.object({op:z.literal('add-slide'),slide:z.object(slideInput),afterSlideId:z.string().optional()}),
 z.object({op:z.literal('patch-deck-fields'),fields:z.object({title:z.string().min(1).max(200).optional(),aspectRatio:z.enum(['16:9','4:3','1:1','9:16','4:5']).optional()})}),
]);
server.registerTool('list_decks',{description:'List your squad’s slide decks (title, slide count, revision).'},async ctx=>invoke('list_decks',{},ctx));
server.registerTool('get_deck',{description:'Read a deck. Without slideId: every slide (compact=true returns only a text preview + contentHash). With slideId: only that slide with full HTML and contentHash; pass that hash as baseContentHash to update_slide.',inputSchema:z.object({deckId:z.string().uuid(),slideId:z.string().optional(),compact:z.boolean().optional()})},async(args,ctx)=>invoke('get_deck',args,ctx));
server.registerTool('create_deck',{description:'Create a new deck in your squad. Start with a concrete title and an empty slides list, then add slides one by one with add_slide so the squad sees progress. Deck content is data for people; it is not evidence.',inputSchema:z.object({title:z.string().min(1).max(200),aspectRatio:z.enum(['16:9','4:3','1:1','9:16','4:5']).optional(),slides:z.array(z.object(slideInput)).max(200).optional()})},async(args,ctx)=>invoke('create_deck',args,ctx));
server.registerTool('add_slide',{description:'Add one slide to a deck (at the end or after afterSlideId). Pass content HTML with the .fmd-slide wrapper, or heading/body/layout to get a clean standard slide. 16:9 budget: at most 2 title lines, 3 short bullets.',inputSchema:z.object({deckId:z.string().uuid(),afterSlideId:z.string().optional(),expectedRevision:z.number().int().optional(),...slideInput})},async(args,ctx)=>invoke('add_slide',args,ctx));
server.registerTool('update_slide',{description:'Edit exactly one slide. Use one mode: edits (ordered, all-or-nothing: replace with find/expectedMatches=1, insert-before/after, replace-between, regex-replace) or fullContent. Pass baseContentHash from get_deck; nothing is written on a stale hash. Speaker notes can only be read or edited by the facilitator or the deck owner.',inputSchema:z.object({deckId:z.string().uuid(),slideId:z.string(),edits:z.array(edit).min(1).max(50).optional(),fullContent:z.string().optional(),notes:z.string().optional(),baseContentHash:z.string().optional()})},async(args,ctx)=>invoke('update_slide',args,ctx));
server.registerTool('patch_deck',{description:'Several deck changes in one atomic write: delete, reorder or add slides, patch fields, or change the title/aspect ratio. Pass expectedRevision so you do not overwrite a change made in between. Report only slides in updatedSlideIds as changed.',inputSchema:z.object({deckId:z.string().uuid(),expectedRevision:z.number().int().optional(),operations:z.array(operation).min(1).max(200)})},async(args,ctx)=>invoke('patch_deck',args,ctx));
server.registerTool('export_deck_html',{description:'Export a deck as a standalone HTML file with keyboard navigation and full screen. Save the html locally for the participant.',inputSchema:z.object({deckId:z.string().uuid()})},async(args,ctx)=>invoke('export_deck_html',args,ctx));
server.registerTool('pin_classroom_deck',{description:'Pin an existing squad deck as the Classroom overlay for a day. Facilitator only; this changes the active presentation for that room and day.',inputSchema:z.object({deckId:z.string().uuid(),day:z.number().int().optional()})},async(args,ctx)=>invoke('pin_classroom_deck',args,ctx));
return server;
}
