import {fail} from './store.mjs';
export class Proof {
 constructor(base,{staleRetryDelays=[300,800,1500]}={}){this.base=base;this.staleRetryDelays=staleRetryDelays;}
 async request(route,token,body,key){for(let attempt=0;;attempt++){const res=await fetch(this.base+route,{method:body?'POST':'GET',headers:{'content-type':'application/json','x-proof-client-version':'0.30.0','x-proof-client-build':'academy-proof-fb257875','x-proof-client-protocol':'3',...(token?{authorization:`Bearer ${token}`} :{}),...(key?{'Idempotency-Key':key}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(18000)});const text=await res.text();let data;try{data=JSON.parse(text);}catch{fail(502,`Proof gaf geen JSON (${res.status}).`);}if(res.status===409&&(data.code==='PROJECTION_STALE'||data.code==='STALE_BASE')&&attempt<this.staleRetryDelays.length){console.warn('[academy] proof projection stale, retrying',{route,attempt:attempt+1,code:data.code});await new Promise(resolve=>setTimeout(resolve,this.staleRetryDelays[attempt]));continue;}if(!res.ok){console.error('[academy] proof request failed',{route,status:res.status,body:text.slice(0,300)});fail(res.status,`Proof ${route} -> ${res.status}: ${text.slice(0,300)}`);}return data;}}
 async create(markdown,title){markdown=markdown.replace(/^(#{1,6} .+)\n(?=\S)/gm,'$1\n\n');const d=await this.request('/documents',null,{markdown,title,role:'editor'});const c=await this.request(`/documents/${d.slug}/access-links`,d.ownerSecret,{role:'commenter'});return {slug:d.slug,owner:d.ownerSecret,editor:d.accessToken,commenter:c.accessToken};}
 async createBoard(markdown,title){const doc=await this.create(markdown,title);const v=await this.request(`/documents/${doc.slug}/access-links`,doc.owner,{role:'viewer'});return {...doc,viewer:v.accessToken};}
 stored(p){return this.request(`/api/documents/${p.slug}`,p.editor);}
 // Pause bumps Proof's access epoch and drops live sockets, so collab sessions minted while the board was open can no longer write on any instance.
 async fence(p){await this.request(`/documents/${p.slug}/pause`,p.owner,{});await this.request(`/documents/${p.slug}/resume`,p.owner,{});}
 state(r){return this.request(`/documents/${r.proof.slug}/state`,r.proof.editor);}
 async comment(r,by,text,quote,key){if(!quote){const state=await this.state(r);quote=state.markdown.split('\n').find(line=>line.trim()).replace(/^#+\s*/,'').trim();}return this.request(`/documents/${r.proof.slug}/bridge/comments`,r.proof.commenter,{by,text,quote},key);}
 suggest(r,by,quote,content,key){return this.request(`/documents/${r.proof.slug}/bridge/suggestions`,r.proof.commenter,{by,kind:'replace',quote,content},key);}
 suggestionReview(r,decision,markId,by,key){return this.request(`/api/agent/${r.proof.slug}/marks/${decision}`,r.proof.editor,{markId,by},key);}
}
