import { randomBytes, randomUUID, createHash } from 'node:crypto';
import { mkdirSync,readFileSync,writeFileSync,renameSync,existsSync } from 'node:fs';
import path from 'node:path';
export const secret=()=>randomBytes(32).toString('hex');
export const hash=t=>createHash('sha256').update(t).digest('hex');
export function fail(status,message){throw Object.assign(new Error(message),{status});}
export const MAX_SQUAD_SIZE=12;
export const MIN_PRACTICE_MEMBERS=4;
export const SOFT_DEFAULT_SQUAD=5;
export class Store {
 constructor(dir){this.dir=dir;mkdirSync(dir,{recursive:true,mode:0o700});this.file=path.join(dir,'rooms.json');this.data=existsSync(this.file)?JSON.parse(readFileSync(this.file,'utf8')):{rooms:{},sessions:{},facilitators:{}};this.data.facilitators??={};this.live=new Map();this.loginStates=new Map();}
 save(){writeFileSync(this.file+'.tmp',JSON.stringify(this.data),{mode:0o600});renameSync(this.file+'.tmp',this.file);}
 session(roomId,personId,kind,displayName){const token=secret();this.data.sessions[hash(token)]={roomId,personId,kind,displayName,expiresAt:Date.now()+12*60*60*1000};this.save();return token;}
 auth(token,kind){const s=this.data.sessions[hash(token||'')];if(!s||(s.expiresAt&&s.expiresAt<Date.now())||kind&&s.kind!==kind)fail(401,'Geen geldige toegang. Meld je opnieuw aan.');const r=this.data.rooms[s.roomId];if(!r)fail(401,'Kamer bestaat niet.');return {s,r,p:r.members.find(m=>m.id===s.personId)};}
 facilitatorLogin(identity){const now=Date.now();for(const [key,facilitator] of Object.entries(this.data.facilitators))if(facilitator.expiresAt<now)delete this.data.facilitators[key];const token=secret();this.data.facilitators[hash(token)]={...identity,expiresAt:now+12*60*60*1000};this.save();return token;}
 facilitator(token){const key=hash(token||''),identity=this.data.facilitators[key];if(!identity)return null;if(identity.expiresAt<Date.now()){delete this.data.facilitators[key];this.save();return null;}const {sub,email,name,domain}=identity;return {sub,email,name,domain};}
 facilitatorLogout(token){delete this.data.facilitators[hash(token||'')];this.save();}
 loginStateSave({stateHash,nonce,codeVerifier,expiresAt}){for(const [key,record] of this.loginStates)if(record.expiresAt<Date.now())this.loginStates.delete(key);this.loginStates.set(stateHash,{nonce,codeVerifier,expiresAt});}
 loginStateTake(stateHash){const record=this.loginStates.get(stateHash);if(!record)return null;this.loginStates.delete(stateHash);return record.expiresAt<Date.now()?null:{nonce:record.nonce,codeVerifier:record.codeVerifier,expiresAt:record.expiresAt};}
 create(name,proof,createdBy){const id=randomUUID();const code=randomBytes(5).toString('hex').toUpperCase();const r={id,code,name,proof,createdBy:createdBy||null,createdAt:Date.now(),roundSeconds:1500,members:[],driver:0,round:1,phase:'Plan',day:1,mode:'lesson',running:false,remaining:1500,deadline:null,evidence:[],handoffs:[],version:1};this.data.rooms[id]=r;const token=this.session(id,'facilitator','browser',createdBy?.name);return {token,roomId:id,code};}
 join(code,name){const r=Object.values(this.data.rooms).find(r=>r.code===code.toUpperCase());if(!r)fail(404,'Kamercode niet gevonden.');const existing=r.members.find(m=>m.name.toLowerCase()===name.toLowerCase());if(existing){const token=this.session(r.id,existing.id,'browser');return {token,roomId:r.id,rejoined:true};}if(r.members.length>=MAX_SQUAD_SIZE)fail(409,`Squad is vol (maximaal ${MAX_SQUAD_SIZE}).`);const p={id:randomUUID(),name,help:false,quiz:null,route:'standard',progressByDay:{},lastMcp:null};r.members.push(p);r.version++;const token=this.session(r.id,p.id,'browser');return {token,roomId:r.id};}
 control(r,action,value,now=Date.now()){if(action==='start'){if(r.members.length<MIN_PRACTICE_MEMBERS)fail(409,`Wacht op minimaal ${MIN_PRACTICE_MEMBERS} deelnemers.`);if(!r.running){r.deadline=now+r.remaining*1000;r.running=true;}}else if(action==='pause'){r.remaining=this.remaining(r,now);r.running=false;r.deadline=null;}else if(action==='next'){if(r.members.length<MIN_PRACTICE_MEMBERS)fail(409,`Wacht op minimaal ${MIN_PRACTICE_MEMBERS} deelnemers.`);r.driver=(r.driver+1)%r.members.length;r.round++;r.running=false;r.remaining=r.roundSeconds||1500;r.deadline=null;}else if(action==='shuffle'){if(!r.members.length)fail(409,'Nog geen deelnemers om rollen te schudden.');if(r.members.length===1){r.driver=0;}else{let next=r.driver;for(let attempt=0;attempt<16&&next===r.driver;attempt++)next=Math.floor(Math.random()*r.members.length);r.driver=next;}}else if(action==='time'){if(!Number.isInteger(value)||value<0||value>7200)fail(400,'Kies een tijd tussen 0 en 120 minuten.');r.remaining=value;if(r.running)r.deadline=now+value*1000;}else if(action==='duration'){if(!Number.isInteger(value)||value<60||value>7200)fail(400,'Kies een tijd tussen 0 en 120 minuten.');r.roundSeconds=value;}else if(action==='phase'){if(!['Plan','Design','Build','Test','Deploy','Maintain'].includes(value))fail(400,'Onbekende fase.');r.phase=value;}else if(action==='day'){if(!Number.isInteger(value)||value<1||value>5)fail(400,'Kies supportdag 1–5.');r.day=value;for(const member of r.members){const progress=member.progressByDay?.[String(value)];member.route=progress?.route||'standard';member.quiz=progress?.quizScore!=null?{score:progress.quizScore,at:progress.quizAt,day:value}:null;}}else if(action==='mode'){if(!['lesson','solo','squad','review'].includes(value))fail(400,'Onbekende werkvorm.');r.mode=value;}else fail(400,'Onbekende actie.');r.version++;this.save();}
 attachFacilitator(roomId,displayName){const r=this.data.rooms[roomId];if(!r)fail(404,'Kamer bestaat niet.');return {token:this.session(roomId,'facilitator','browser',displayName),roomId,code:r.code};}
 remaining(r,now=Date.now()){return r.running?Math.max(0,Math.ceil((r.deadline-now)/1000)):r.remaining;}
 overview(){return Object.values(this.data.rooms).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)).map(r=>({id:r.id,name:r.name,code:r.code,createdBy:r.createdBy||null,createdAt:r.createdAt||null,round:r.round,phase:r.phase,day:r.day,mode:r.mode,running:r.running,remaining:this.remaining(r),roundSeconds:r.roundSeconds||1500,driver:r.members[r.driver]?.name||null,members:r.members.map((m,i)=>({id:m.id,name:m.name,role:i===r.driver?'Driver':'Navigator',online:(this.live.get(m.id)||0)>Date.now()-12000,help:m.help,lastMcp:m.lastMcp||null})),evidence:r.evidence.length,handoffs:r.handoffs.length}));}
 view(r,s){return {id:r.id,name:r.name,code:r.code,round:r.round,phase:r.phase,day:r.day,mode:r.mode,running:r.running,remaining:this.remaining(r),roundSeconds:r.roundSeconds||1500,serverTime:Date.now(),deadline:r.deadline,version:r.version,documentSlug:r.proof.slug,members:r.members.map((m,i)=>({id:m.id,name:m.name,role:i===r.driver?'Driver':'Navigator',online:(this.live.get(m.id)||0)>Date.now()-12000,help:m.help,...(s.personId==='facilitator'?{quiz:m.quiz}:{} )})),me:s.personId==='facilitator'?{id:'facilitator',name:s.displayName||'Facilitator',role:'Facilitator'}:{...r.members.find(m=>m.id===s.personId),role:r.members[r.driver]?.id===s.personId?'Driver':'Navigator'},evidence:r.evidence,handoffs:r.handoffs};}
}
