import { randomBytes, randomUUID, createHash } from 'node:crypto';
import { mkdirSync,readFileSync,writeFileSync,renameSync,existsSync } from 'node:fs';
import path from 'node:path';
import {awaitingReview} from './proof-trail.mjs';
import { DAY_COUNT } from '../content/days/index.mjs';
import {boardView} from './debrief-board.mjs';
import { parseCourse } from '../content/days/course.mjs';
export const secret=()=>randomBytes(32).toString('hex');
export const hash=t=>createHash('sha256').update(t).digest('hex');
export function fail(status,message){throw Object.assign(new Error(message),{status});}
export const MAX_SQUAD_SIZE=12;
export const MIN_PRACTICE_MEMBERS=4;
export const SOFT_DEFAULT_SQUAD=5;
export const LOCAL_SCHEMA_VERSION=2;
export const DUPLICATE_PARTICIPANT_MESSAGE='Deze naam is al in gebruik in deze kamer. Gebruik je persoonlijke deelnemerslink om opnieuw in te loggen.';
export const INVALID_PARTICIPANT_ACCESS_MESSAGE='Deze persoonlijke deelnemerslink is ongeldig.';
const selectDay=(r,day)=>{r.day=day;for(const member of r.members){const progress=member.progressByDay?.[String(day)];member.route=progress?.route||'standard';member.quiz=progress?.quizScore!=null?{score:progress.quizScore,at:progress.quizAt,day}:null;}};
export const READ_ONLY_MESSAGE='Je cohorttoegang is alleen-lezen. Je kunt je werk nog bekijken en exporteren.';
export const COHORT_ROOM_JOIN_MESSAGE='Deze kamer hoort bij een cohort. Log in met je persoonlijke cohortcode.';
export const writable=context=>{if(context.s.readOnly)fail(403,READ_ONLY_MESSAGE);return context;};
export const COHORT_SEAT_ACCESS_MESSAGE='Je logt in met je persoonlijke cohortcode; een aparte deelnemerslink is niet nodig.';
const participantView=participant=>{const {access,...view}=participant;return view;};
export class Store {
 constructor(dir,{now=Date.now}={}){this.now=now;this.dir=dir;mkdirSync(dir,{recursive:true,mode:0o700});this.file=path.join(dir,'rooms.json');this.data=existsSync(this.file)?JSON.parse(readFileSync(this.file,'utf8')):{rooms:{},sessions:{},facilitators:{}};this.data.schemaVersion??=LOCAL_SCHEMA_VERSION;this.data.facilitators??={};this.data.cohorts??={};this.data.accessCodes??={};this.data.attempts??={};this.live=new Map();this.loginStates=new Map();}
 save(){writeFileSync(this.file+'.tmp',JSON.stringify(this.data),{mode:0o600});renameSync(this.file+'.tmp',this.file);}
 session(roomId,personId,kind,displayName,{expiresAt=this.now()+12*60*60*1000,readOnly=false}={}){const token=secret();this.data.sessions[hash(token)]={roomId,personId,kind,displayName,expiresAt,...(readOnly?{readOnly:true}:{})};this.save();return token;}
 auth(token,kind){const s=this.data.sessions[hash(token||'')];if(!s||(s.expiresAt&&s.expiresAt<=this.now())||kind&&s.kind!==kind)fail(401,'Geen geldige toegang. Meld je opnieuw aan.');const r=this.data.rooms[s.roomId];if(!r)fail(401,'Kamer bestaat niet.');return {s,r,p:r.members.find(m=>m.id===s.personId)};}
 facilitatorLogin(identity){const now=Date.now();for(const [key,facilitator] of Object.entries(this.data.facilitators))if(facilitator.expiresAt<now)delete this.data.facilitators[key];const token=secret();this.data.facilitators[hash(token)]={...identity,expiresAt:now+12*60*60*1000};this.save();return token;}
 facilitator(token){const key=hash(token||''),identity=this.data.facilitators[key];if(!identity)return null;if(identity.expiresAt<Date.now()){delete this.data.facilitators[key];this.save();return null;}const {sub,email,name,domain}=identity;return {sub,email,name,domain};}
 facilitatorLogout(token){delete this.data.facilitators[hash(token||'')];this.save();}
 loginStateSave({stateHash,nonce,codeVerifier,expiresAt}){for(const [key,record] of this.loginStates)if(record.expiresAt<Date.now())this.loginStates.delete(key);this.loginStates.set(stateHash,{nonce,codeVerifier,expiresAt});}
 loginStateTake(stateHash){const record=this.loginStates.get(stateHash);if(!record)return null;this.loginStates.delete(stateHash);return record.expiresAt<Date.now()?null:{nonce:record.nonce,codeVerifier:record.codeVerifier,expiresAt:record.expiresAt};}
 create(name,proof,createdBy){const id=randomUUID();const code=randomBytes(5).toString('hex').toUpperCase();const r={id,code,name,proof,createdBy:createdBy||null,createdAt:Date.now(),roundSeconds:1500,members:[],driver:0,round:1,phase:'Plan',day:1,mode:'lesson',running:false,remaining:1500,deadline:null,evidence:[],handoffs:[],version:1};this.data.rooms[id]=r;const token=this.session(id,'facilitator','browser',createdBy?.name);return {token,roomId:id,code};}
 join(code,name){const r=Object.values(this.data.rooms).find(r=>r.code===code.toUpperCase());if(!r)fail(404,'Kamercode niet gevonden.');if(r.cohortId)fail(403,COHORT_ROOM_JOIN_MESSAGE);const existing=r.members.find(m=>m.name.toLowerCase()===name.toLowerCase());if(existing)fail(409,DUPLICATE_PARTICIPANT_MESSAGE);if(r.members.length>=MAX_SQUAD_SIZE)fail(409,`Squad is vol (maximaal ${MAX_SQUAD_SIZE}).`);const resumeToken=secret();const p={id:randomUUID(),name,help:false,quiz:null,route:'standard',progressByDay:{},lastMcp:null,access:{resumeSecretHash:hash(resumeToken)}};r.members.push(p);r.version++;const token=this.session(r.id,p.id,'browser');return {token,roomId:r.id,resumeToken};}
 resumeParticipant(resumeToken){const resumeSecretHash=hash(resumeToken||'');for(const r of Object.values(this.data.rooms)){const p=r.members.find(member=>member.access?.resumeSecretHash===resumeSecretHash);if(p){const token=this.session(r.id,p.id,'browser',p.name);return {token,roomId:r.id,resumed:true};}}fail(401,INVALID_PARTICIPANT_ACCESS_MESSAGE);}
 rotateParticipantAccess(token){const {p}=writable(this.auth(token,'browser'));if(!p)fail(403,'Gebruik hiervoor een deelnemerssessie.');if(p.cohortMemberId)fail(409,COHORT_SEAT_ACCESS_MESSAGE);const resumeToken=secret();p.access={resumeSecretHash:hash(resumeToken)};this.save();return {resumeToken};}
 control(r,action,value,now=Date.now()){if(action==='start'){if(r.members.length<MIN_PRACTICE_MEMBERS)fail(409,`Wacht op minimaal ${MIN_PRACTICE_MEMBERS} deelnemers.`);if(!r.running){r.deadline=now+r.remaining*1000;r.running=true;}}else if(action==='pause'){r.remaining=this.remaining(r,now);r.running=false;r.deadline=null;}else if(action==='next'){if(r.members.length<MIN_PRACTICE_MEMBERS)fail(409,`Wacht op minimaal ${MIN_PRACTICE_MEMBERS} deelnemers.`);r.driver=(r.driver+1)%r.members.length;r.round++;r.running=false;r.remaining=r.roundSeconds||1500;r.deadline=null;}else if(action==='shuffle'){if(!r.members.length)fail(409,'Nog geen deelnemers om rollen te schudden.');if(r.members.length===1){r.driver=0;}else{let next=r.driver;for(let attempt=0;attempt<16&&next===r.driver;attempt++)next=Math.floor(Math.random()*r.members.length);r.driver=next;}}else if(action==='time'){if(!Number.isInteger(value)||value<0||value>7200)fail(400,'Kies een tijd tussen 0 en 120 minuten.');r.remaining=value;if(r.running)r.deadline=now+value*1000;}else if(action==='duration'){if(!Number.isInteger(value)||value<60||value>7200)fail(400,'Kies een tijd tussen 0 en 120 minuten.');r.roundSeconds=value;}else if(action==='phase'){if(!['Plan','Design','Build','Test','Deploy','Maintain'].includes(value))fail(400,'Onbekende fase.');r.phase=value;}else if(action==='day'){if(r.course?!r.course.days.some(entry=>entry.day===value):!Number.isInteger(value)||value<1||value>DAY_COUNT)fail(400,r.course?`Dag ${value} zit niet in de cursus.`:`Kies dag 1–${DAY_COUNT}.`);selectDay(r,value);}else if(action==='course'){if(value==null)delete r.course;else{r.course=parseCourse(value);if(!r.course.days.some(entry=>entry.day===r.day))selectDay(r,r.course.days[0].day);}}else if(action==='mode'){if(!['lesson','solo','squad','review'].includes(value))fail(400,'Onbekende werkvorm.');r.mode=value;}else if(action==='chat'){if(typeof value!=='boolean')fail(400,'Zet de chat aan of uit.');r.chat=value;}else fail(400,'Onbekende actie.');r.version++;this.save();}
 attachFacilitator(roomId,displayName){const r=this.data.rooms[roomId];if(!r)fail(404,'Kamer bestaat niet.');return {token:this.session(roomId,'facilitator','browser',displayName),roomId,code:r.code};}
 remaining(r,now=Date.now()){return r.running?Math.max(0,Math.ceil((r.deadline-now)/1000)):r.remaining;}
 overview(){return Object.values(this.data.rooms).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)).map(r=>({id:r.id,name:r.name,code:r.code,createdBy:r.createdBy||null,createdAt:r.createdAt||null,round:r.round,phase:r.phase,day:r.day,mode:r.mode,running:r.running,remaining:this.remaining(r),roundSeconds:r.roundSeconds||1500,driver:r.members[r.driver]?.name||null,members:r.members.map((m,i)=>({id:m.id,name:m.name,role:i===r.driver?'Driver':'Navigator',online:(this.live.get(m.id)||0)>Date.now()-12000,help:m.help,lastMcp:m.lastMcp||null})),evidence:r.evidence.length,awaitingReview:awaitingReview(r).length,handoffs:r.handoffs.length,board:r.board?.status||null}));}
 view(r,s){return {id:r.id,name:r.name,code:r.members.find(m=>m.id===s.personId)?.cohortMemberId?null:r.code,round:r.round,phase:r.phase,day:r.day,course:r.course??null,mode:r.mode,chat:r.chat!==false,running:r.running,remaining:this.remaining(r),roundSeconds:r.roundSeconds||1500,serverTime:Date.now(),deadline:r.deadline,version:r.version,readOnly:Boolean(s.readOnly),documentSlug:r.proof.slug,board:boardView(r.board),members:r.members.map((m,i)=>({id:m.id,name:m.name,role:i===r.driver?'Driver':'Navigator',online:(this.live.get(m.id)||0)>Date.now()-12000,help:m.help,...(s.personId==='facilitator'?{quiz:m.quiz}:{} )})),me:s.personId==='facilitator'?{id:'facilitator',name:s.displayName||'Facilitator',role:'Facilitator'}:{...participantView(r.members.find(m=>m.id===s.personId)),role:r.members[r.driver]?.id===s.personId?'Driver':'Navigator'},evidence:r.evidence,handoffs:r.handoffs};}
}
